/*
 * Pescheck API
 *
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Pescheck.Client.Client.FileParameter;
using OpenAPIDateConverter = Pescheck.Client.Client.OpenAPIDateConverter;

namespace Pescheck.Client.Model
{
    /// <summary>
    /// Minimal check entry shape for screening list items. No config/input/etc.
    /// </summary>
    [DataContract(Name = "V2ScreeningCheckListItem")]
    public partial class V2ScreeningCheckListItem : IValidatableObject
    {
        /// <summary>
        /// * &#x60;addresscheck&#x60; - addresscheck * &#x60;adversemediacheck&#x60; - adversemediacheck * &#x60;bigcheck&#x60; - bigcheck * &#x60;criminalrecordscheck&#x60; - criminalrecordscheck * &#x60;criminalrecordsuploadcheck&#x60; - criminalrecordsuploadcheck * &#x60;customintegritycheck&#x60; - customintegritycheck * &#x60;cvcheck&#x60; - cvcheck * &#x60;edrcheck&#x60; - edrcheck * &#x60;focumcheck&#x60; - focumcheck * &#x60;id2check&#x60; - id2check * &#x60;idcheck&#x60; - idcheck * &#x60;integritycheck&#x60; - integritycheck * &#x60;openhealthcarecheck&#x60; - openhealthcarecheck * &#x60;permissioncheck&#x60; - permissioncheck * &#x60;pescheckadversemediacheck&#x60; - pescheckadversemediacheck * &#x60;qualificationcheck&#x60; - qualificationcheck * &#x60;righttoworkcheck&#x60; - righttoworkcheck * &#x60;vogcheck&#x60; - vogcheck * &#x60;watchlist2check&#x60; - watchlist2check * &#x60;watchlistcheck&#x60; - watchlistcheck * &#x60;workreferencecheck&#x60; - workreferencecheck * &#x60;worldwidecreditcheck&#x60; - worldwidecreditcheck
        /// </summary>
        /// <value>* &#x60;addresscheck&#x60; - addresscheck * &#x60;adversemediacheck&#x60; - adversemediacheck * &#x60;bigcheck&#x60; - bigcheck * &#x60;criminalrecordscheck&#x60; - criminalrecordscheck * &#x60;criminalrecordsuploadcheck&#x60; - criminalrecordsuploadcheck * &#x60;customintegritycheck&#x60; - customintegritycheck * &#x60;cvcheck&#x60; - cvcheck * &#x60;edrcheck&#x60; - edrcheck * &#x60;focumcheck&#x60; - focumcheck * &#x60;id2check&#x60; - id2check * &#x60;idcheck&#x60; - idcheck * &#x60;integritycheck&#x60; - integritycheck * &#x60;openhealthcarecheck&#x60; - openhealthcarecheck * &#x60;permissioncheck&#x60; - permissioncheck * &#x60;pescheckadversemediacheck&#x60; - pescheckadversemediacheck * &#x60;qualificationcheck&#x60; - qualificationcheck * &#x60;righttoworkcheck&#x60; - righttoworkcheck * &#x60;vogcheck&#x60; - vogcheck * &#x60;watchlist2check&#x60; - watchlist2check * &#x60;watchlistcheck&#x60; - watchlistcheck * &#x60;workreferencecheck&#x60; - workreferencecheck * &#x60;worldwidecreditcheck&#x60; - worldwidecreditcheck</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CheckTypeEnum
        {
            /// <summary>
            /// Enum Addresscheck for value: addresscheck
            /// </summary>
            [EnumMember(Value = "addresscheck")]
            Addresscheck = 1,

            /// <summary>
            /// Enum Adversemediacheck for value: adversemediacheck
            /// </summary>
            [EnumMember(Value = "adversemediacheck")]
            Adversemediacheck = 2,

            /// <summary>
            /// Enum Bigcheck for value: bigcheck
            /// </summary>
            [EnumMember(Value = "bigcheck")]
            Bigcheck = 3,

            /// <summary>
            /// Enum Criminalrecordscheck for value: criminalrecordscheck
            /// </summary>
            [EnumMember(Value = "criminalrecordscheck")]
            Criminalrecordscheck = 4,

            /// <summary>
            /// Enum Criminalrecordsuploadcheck for value: criminalrecordsuploadcheck
            /// </summary>
            [EnumMember(Value = "criminalrecordsuploadcheck")]
            Criminalrecordsuploadcheck = 5,

            /// <summary>
            /// Enum Customintegritycheck for value: customintegritycheck
            /// </summary>
            [EnumMember(Value = "customintegritycheck")]
            Customintegritycheck = 6,

            /// <summary>
            /// Enum Cvcheck for value: cvcheck
            /// </summary>
            [EnumMember(Value = "cvcheck")]
            Cvcheck = 7,

            /// <summary>
            /// Enum Edrcheck for value: edrcheck
            /// </summary>
            [EnumMember(Value = "edrcheck")]
            Edrcheck = 8,

            /// <summary>
            /// Enum Focumcheck for value: focumcheck
            /// </summary>
            [EnumMember(Value = "focumcheck")]
            Focumcheck = 9,

            /// <summary>
            /// Enum Id2check for value: id2check
            /// </summary>
            [EnumMember(Value = "id2check")]
            Id2check = 10,

            /// <summary>
            /// Enum Idcheck for value: idcheck
            /// </summary>
            [EnumMember(Value = "idcheck")]
            Idcheck = 11,

            /// <summary>
            /// Enum Integritycheck for value: integritycheck
            /// </summary>
            [EnumMember(Value = "integritycheck")]
            Integritycheck = 12,

            /// <summary>
            /// Enum Openhealthcarecheck for value: openhealthcarecheck
            /// </summary>
            [EnumMember(Value = "openhealthcarecheck")]
            Openhealthcarecheck = 13,

            /// <summary>
            /// Enum Permissioncheck for value: permissioncheck
            /// </summary>
            [EnumMember(Value = "permissioncheck")]
            Permissioncheck = 14,

            /// <summary>
            /// Enum Pescheckadversemediacheck for value: pescheckadversemediacheck
            /// </summary>
            [EnumMember(Value = "pescheckadversemediacheck")]
            Pescheckadversemediacheck = 15,

            /// <summary>
            /// Enum Qualificationcheck for value: qualificationcheck
            /// </summary>
            [EnumMember(Value = "qualificationcheck")]
            Qualificationcheck = 16,

            /// <summary>
            /// Enum Righttoworkcheck for value: righttoworkcheck
            /// </summary>
            [EnumMember(Value = "righttoworkcheck")]
            Righttoworkcheck = 17,

            /// <summary>
            /// Enum Vogcheck for value: vogcheck
            /// </summary>
            [EnumMember(Value = "vogcheck")]
            Vogcheck = 18,

            /// <summary>
            /// Enum Watchlist2check for value: watchlist2check
            /// </summary>
            [EnumMember(Value = "watchlist2check")]
            Watchlist2check = 19,

            /// <summary>
            /// Enum Watchlistcheck for value: watchlistcheck
            /// </summary>
            [EnumMember(Value = "watchlistcheck")]
            Watchlistcheck = 20,

            /// <summary>
            /// Enum Workreferencecheck for value: workreferencecheck
            /// </summary>
            [EnumMember(Value = "workreferencecheck")]
            Workreferencecheck = 21,

            /// <summary>
            /// Enum Worldwidecreditcheck for value: worldwidecreditcheck
            /// </summary>
            [EnumMember(Value = "worldwidecreditcheck")]
            Worldwidecreditcheck = 22
        }


        /// <summary>
        /// * &#x60;addresscheck&#x60; - addresscheck * &#x60;adversemediacheck&#x60; - adversemediacheck * &#x60;bigcheck&#x60; - bigcheck * &#x60;criminalrecordscheck&#x60; - criminalrecordscheck * &#x60;criminalrecordsuploadcheck&#x60; - criminalrecordsuploadcheck * &#x60;customintegritycheck&#x60; - customintegritycheck * &#x60;cvcheck&#x60; - cvcheck * &#x60;edrcheck&#x60; - edrcheck * &#x60;focumcheck&#x60; - focumcheck * &#x60;id2check&#x60; - id2check * &#x60;idcheck&#x60; - idcheck * &#x60;integritycheck&#x60; - integritycheck * &#x60;openhealthcarecheck&#x60; - openhealthcarecheck * &#x60;permissioncheck&#x60; - permissioncheck * &#x60;pescheckadversemediacheck&#x60; - pescheckadversemediacheck * &#x60;qualificationcheck&#x60; - qualificationcheck * &#x60;righttoworkcheck&#x60; - righttoworkcheck * &#x60;vogcheck&#x60; - vogcheck * &#x60;watchlist2check&#x60; - watchlist2check * &#x60;watchlistcheck&#x60; - watchlistcheck * &#x60;workreferencecheck&#x60; - workreferencecheck * &#x60;worldwidecreditcheck&#x60; - worldwidecreditcheck
        /// </summary>
        /// <value>* &#x60;addresscheck&#x60; - addresscheck * &#x60;adversemediacheck&#x60; - adversemediacheck * &#x60;bigcheck&#x60; - bigcheck * &#x60;criminalrecordscheck&#x60; - criminalrecordscheck * &#x60;criminalrecordsuploadcheck&#x60; - criminalrecordsuploadcheck * &#x60;customintegritycheck&#x60; - customintegritycheck * &#x60;cvcheck&#x60; - cvcheck * &#x60;edrcheck&#x60; - edrcheck * &#x60;focumcheck&#x60; - focumcheck * &#x60;id2check&#x60; - id2check * &#x60;idcheck&#x60; - idcheck * &#x60;integritycheck&#x60; - integritycheck * &#x60;openhealthcarecheck&#x60; - openhealthcarecheck * &#x60;permissioncheck&#x60; - permissioncheck * &#x60;pescheckadversemediacheck&#x60; - pescheckadversemediacheck * &#x60;qualificationcheck&#x60; - qualificationcheck * &#x60;righttoworkcheck&#x60; - righttoworkcheck * &#x60;vogcheck&#x60; - vogcheck * &#x60;watchlist2check&#x60; - watchlist2check * &#x60;watchlistcheck&#x60; - watchlistcheck * &#x60;workreferencecheck&#x60; - workreferencecheck * &#x60;worldwidecreditcheck&#x60; - worldwidecreditcheck</value>
        [DataMember(Name = "check_type", IsRequired = true, EmitDefaultValue = true)]
        public CheckTypeEnum CheckType { get; set; }

        /// <summary>
        /// Returns false as CheckType should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCheckType()
        {
            return false;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="V2ScreeningCheckListItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public V2ScreeningCheckListItem()
        {
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; private set; }

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; private set; }

        /// <summary>
        /// Returns false as Status should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStatus()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2ScreeningCheckListItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CheckType: ").Append(CheckType).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
