/*
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.pescheck.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.pescheck.client.model.V2CheckField;
import io.pescheck.client.model.V2Money;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2CheckInfo
 */
public class V2CheckInfoTest {
    private final V2CheckInfo model = new V2CheckInfo();

    /**
     * Model tests for V2CheckInfo
     */
    @Test
    public void testV2CheckInfo() {
        // TODO: test V2CheckInfo
    }

    /**
     * Test the property 'checkType'
     */
    @Test
    public void checkTypeTest() {
        // TODO: test checkType
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'hasConfig'
     */
    @Test
    public void hasConfigTest() {
        // TODO: test hasConfig
    }

    /**
     * Test the property 'isSystemManaged'
     */
    @Test
    public void isSystemManagedTest() {
        // TODO: test isSystemManaged
    }

    /**
     * Test the property 'requiresChecks'
     */
    @Test
    public void requiresChecksTest() {
        // TODO: test requiresChecks
    }

    /**
     * Test the property 'supportedCountriesOfWork'
     */
    @Test
    public void supportedCountriesOfWorkTest() {
        // TODO: test supportedCountriesOfWork
    }

    /**
     * Test the property 'supportedCountriesOfResidence'
     */
    @Test
    public void supportedCountriesOfResidenceTest() {
        // TODO: test supportedCountriesOfResidence
    }

    /**
     * Test the property 'defaultPrice'
     */
    @Test
    public void defaultPriceTest() {
        // TODO: test defaultPrice
    }

    /**
     * Test the property 'configFields'
     */
    @Test
    public void configFieldsTest() {
        // TODO: test configFields
    }

    /**
     * Test the property 'inputFields'
     */
    @Test
    public void inputFieldsTest() {
        // TODO: test inputFields
    }

    /**
     * Test the property 'candidateFields'
     */
    @Test
    public void candidateFieldsTest() {
        // TODO: test candidateFields
    }

}
