/*
 * Pescheck API
 *
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pescheck.Client.Model;
using Pescheck.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pescheck.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TokenRefresh
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenRefreshTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenRefresh
        //private TokenRefresh instance;

        public TokenRefreshTests()
        {
            // TODO uncomment below to create an instance of TokenRefresh
            //instance = new TokenRefresh();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenRefresh
        /// </summary>
        [Fact]
        public void TokenRefreshInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenRefresh
            //Assert.IsType<TokenRefresh>(instance);
        }

        /// <summary>
        /// Test the property 'Access'
        /// </summary>
        [Fact]
        public void AccessTest()
        {
            // TODO unit test for the property 'Access'
        }

        /// <summary>
        /// Test the property 'Refresh'
        /// </summary>
        [Fact]
        public void RefreshTest()
        {
            // TODO unit test for the property 'Refresh'
        }
    }
}
