/*
 * Pescheck API
 *
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pescheck.Client.Model;
using Pescheck.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pescheck.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V2ScreeningNoteInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V2ScreeningNoteInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V2ScreeningNoteInput
        //private V2ScreeningNoteInput instance;

        public V2ScreeningNoteInputTests()
        {
            // TODO uncomment below to create an instance of V2ScreeningNoteInput
            //instance = new V2ScreeningNoteInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V2ScreeningNoteInput
        /// </summary>
        [Fact]
        public void V2ScreeningNoteInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" V2ScreeningNoteInput
            //Assert.IsType<V2ScreeningNoteInput>(instance);
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }

        /// <summary>
        /// Test the property 'ProfileCheckId'
        /// </summary>
        [Fact]
        public void ProfileCheckIdTest()
        {
            // TODO unit test for the property 'ProfileCheckId'
        }

        /// <summary>
        /// Test the property 'CheckType'
        /// </summary>
        [Fact]
        public void CheckTypeTest()
        {
            // TODO unit test for the property 'CheckType'
        }
    }
}
