/*
Pescheck API

Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pescheck

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedDivisionReadOnlyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedDivisionReadOnlyList{}

// PaginatedDivisionReadOnlyList struct for PaginatedDivisionReadOnlyList
type PaginatedDivisionReadOnlyList struct {
	Count int32 `json:"count"`
	Next NullableString `json:"next"`
	Previous NullableString `json:"previous"`
	Results []DivisionReadOnly `json:"results"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedDivisionReadOnlyList PaginatedDivisionReadOnlyList

// NewPaginatedDivisionReadOnlyList instantiates a new PaginatedDivisionReadOnlyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedDivisionReadOnlyList(count int32, next NullableString, previous NullableString, results []DivisionReadOnly) *PaginatedDivisionReadOnlyList {
	this := PaginatedDivisionReadOnlyList{}
	this.Count = count
	this.Next = next
	this.Previous = previous
	this.Results = results
	return &this
}

// NewPaginatedDivisionReadOnlyListWithDefaults instantiates a new PaginatedDivisionReadOnlyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedDivisionReadOnlyListWithDefaults() *PaginatedDivisionReadOnlyList {
	this := PaginatedDivisionReadOnlyList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedDivisionReadOnlyList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedDivisionReadOnlyList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedDivisionReadOnlyList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaginatedDivisionReadOnlyList) GetNext() string {
	if o == nil || o.Next.Get() == nil {
		var ret string
		return ret
	}

	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedDivisionReadOnlyList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// SetNext sets field value
func (o *PaginatedDivisionReadOnlyList) SetNext(v string) {
	o.Next.Set(&v)
}

// GetPrevious returns the Previous field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaginatedDivisionReadOnlyList) GetPrevious() string {
	if o == nil || o.Previous.Get() == nil {
		var ret string
		return ret
	}

	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedDivisionReadOnlyList) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// SetPrevious sets field value
func (o *PaginatedDivisionReadOnlyList) SetPrevious(v string) {
	o.Previous.Set(&v)
}

// GetResults returns the Results field value
func (o *PaginatedDivisionReadOnlyList) GetResults() []DivisionReadOnly {
	if o == nil {
		var ret []DivisionReadOnly
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedDivisionReadOnlyList) GetResultsOk() ([]DivisionReadOnly, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedDivisionReadOnlyList) SetResults(v []DivisionReadOnly) {
	o.Results = v
}

func (o PaginatedDivisionReadOnlyList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedDivisionReadOnlyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["next"] = o.Next.Get()
	toSerialize["previous"] = o.Previous.Get()
	toSerialize["results"] = o.Results

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedDivisionReadOnlyList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"next",
		"previous",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedDivisionReadOnlyList := _PaginatedDivisionReadOnlyList{}

	err = json.Unmarshal(data, &varPaginatedDivisionReadOnlyList)

	if err != nil {
		return err
	}

	*o = PaginatedDivisionReadOnlyList(varPaginatedDivisionReadOnlyList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "count")
		delete(additionalProperties, "next")
		delete(additionalProperties, "previous")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedDivisionReadOnlyList struct {
	value *PaginatedDivisionReadOnlyList
	isSet bool
}

func (v NullablePaginatedDivisionReadOnlyList) Get() *PaginatedDivisionReadOnlyList {
	return v.value
}

func (v *NullablePaginatedDivisionReadOnlyList) Set(val *PaginatedDivisionReadOnlyList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedDivisionReadOnlyList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedDivisionReadOnlyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedDivisionReadOnlyList(val *PaginatedDivisionReadOnlyList) *NullablePaginatedDivisionReadOnlyList {
	return &NullablePaginatedDivisionReadOnlyList{value: val, isSet: true}
}

func (v NullablePaginatedDivisionReadOnlyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedDivisionReadOnlyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


