/*
Pescheck API

Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pescheck

import (
	"encoding/json"
)

// checks if the V2CheckField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2CheckField{}

// V2CheckField One config or input field a check accepts via the API.
type V2CheckField struct {
	Name *string `json:"name,omitempty"`
	// \"string\" | \"integer\" | \"number\" | \"boolean\" | \"array\" | \"object\"
	Type *string `json:"type,omitempty"`
	// Whether the request body must include this field.
	Required *bool `json:"required,omitempty"`
	// Allowed values, or null if the field isn't constrained to a set.
	Choices []string `json:"choices,omitempty"`
	HelpText NullableString `json:"help_text,omitempty"`
}

// NewV2CheckField instantiates a new V2CheckField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2CheckField() *V2CheckField {
	this := V2CheckField{}
	return &this
}

// NewV2CheckFieldWithDefaults instantiates a new V2CheckField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2CheckFieldWithDefaults() *V2CheckField {
	this := V2CheckField{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V2CheckField) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2CheckField) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V2CheckField) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V2CheckField) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V2CheckField) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2CheckField) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V2CheckField) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *V2CheckField) SetType(v string) {
	o.Type = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *V2CheckField) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2CheckField) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *V2CheckField) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *V2CheckField) SetRequired(v bool) {
	o.Required = &v
}

// GetChoices returns the Choices field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *V2CheckField) GetChoices() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2CheckField) GetChoicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Choices) {
		return nil, false
	}
	return o.Choices, true
}

// HasChoices returns a boolean if a field has been set.
func (o *V2CheckField) HasChoices() bool {
	if o != nil && !IsNil(o.Choices) {
		return true
	}

	return false
}

// SetChoices gets a reference to the given []string and assigns it to the Choices field.
func (o *V2CheckField) SetChoices(v []string) {
	o.Choices = v
}

// GetHelpText returns the HelpText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *V2CheckField) GetHelpText() string {
	if o == nil || IsNil(o.HelpText.Get()) {
		var ret string
		return ret
	}
	return *o.HelpText.Get()
}

// GetHelpTextOk returns a tuple with the HelpText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2CheckField) GetHelpTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HelpText.Get(), o.HelpText.IsSet()
}

// HasHelpText returns a boolean if a field has been set.
func (o *V2CheckField) HasHelpText() bool {
	if o != nil && o.HelpText.IsSet() {
		return true
	}

	return false
}

// SetHelpText gets a reference to the given NullableString and assigns it to the HelpText field.
func (o *V2CheckField) SetHelpText(v string) {
	o.HelpText.Set(&v)
}
// SetHelpTextNil sets the value for HelpText to be an explicit nil
func (o *V2CheckField) SetHelpTextNil() {
	o.HelpText.Set(nil)
}

// UnsetHelpText ensures that no value is present for HelpText, not even an explicit nil
func (o *V2CheckField) UnsetHelpText() {
	o.HelpText.Unset()
}

func (o V2CheckField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2CheckField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if o.Choices != nil {
		toSerialize["choices"] = o.Choices
	}
	if o.HelpText.IsSet() {
		toSerialize["help_text"] = o.HelpText.Get()
	}
	return toSerialize, nil
}

type NullableV2CheckField struct {
	value *V2CheckField
	isSet bool
}

func (v NullableV2CheckField) Get() *V2CheckField {
	return v.value
}

func (v *NullableV2CheckField) Set(val *V2CheckField) {
	v.value = val
	v.isSet = true
}

func (v NullableV2CheckField) IsSet() bool {
	return v.isSet
}

func (v *NullableV2CheckField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2CheckField(val *V2CheckField) *NullableV2CheckField {
	return &NullableV2CheckField{value: val, isSet: true}
}

func (v NullableV2CheckField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2CheckField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


