/*
Pescheck API

Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pescheck

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// V2CandidateHouseNumber - struct for V2CandidateHouseNumber
type V2CandidateHouseNumber struct {
	String *string
}

// stringAsV2CandidateHouseNumber is a convenience function that returns string wrapped in V2CandidateHouseNumber
func StringAsV2CandidateHouseNumber(v *string) V2CandidateHouseNumber {
	return V2CandidateHouseNumber{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *V2CandidateHouseNumber) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(V2CandidateHouseNumber)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(V2CandidateHouseNumber)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2CandidateHouseNumber) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *V2CandidateHouseNumber) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj V2CandidateHouseNumber) GetActualInstanceValue() (interface{}) {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableV2CandidateHouseNumber struct {
	value *V2CandidateHouseNumber
	isSet bool
}

func (v NullableV2CandidateHouseNumber) Get() *V2CandidateHouseNumber {
	return v.value
}

func (v *NullableV2CandidateHouseNumber) Set(val *V2CandidateHouseNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableV2CandidateHouseNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableV2CandidateHouseNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2CandidateHouseNumber(val *V2CandidateHouseNumber) *NullableV2CandidateHouseNumber {
	return &NullableV2CandidateHouseNumber{value: val, isSet: true}
}

func (v NullableV2CandidateHouseNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2CandidateHouseNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


