/*
Pescheck API

Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pescheck

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ScreeningCheckListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ScreeningCheckListItem{}

// V2ScreeningCheckListItem Minimal check entry shape for screening list items. No config/input/etc.
type V2ScreeningCheckListItem struct {
	Id string `json:"id"`
	// * `addresscheck` - addresscheck * `adversemediacheck` - adversemediacheck * `bigcheck` - bigcheck * `criminalrecordscheck` - criminalrecordscheck * `criminalrecordsuploadcheck` - criminalrecordsuploadcheck * `customintegritycheck` - customintegritycheck * `cvcheck` - cvcheck * `edrcheck` - edrcheck * `focumcheck` - focumcheck * `id2check` - id2check * `idcheck` - idcheck * `integritycheck` - integritycheck * `openhealthcarecheck` - openhealthcarecheck * `permissioncheck` - permissioncheck * `pescheckadversemediacheck` - pescheckadversemediacheck * `qualificationcheck` - qualificationcheck * `righttoworkcheck` - righttoworkcheck * `vogcheck` - vogcheck * `watchlist2check` - watchlist2check * `watchlistcheck` - watchlistcheck * `workreferencecheck` - workreferencecheck * `worldwidecreditcheck` - worldwidecreditcheck
	CheckType string `json:"check_type"`
	Status string `json:"status"`
}

type _V2ScreeningCheckListItem V2ScreeningCheckListItem

// NewV2ScreeningCheckListItem instantiates a new V2ScreeningCheckListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ScreeningCheckListItem(id string, checkType string, status string) *V2ScreeningCheckListItem {
	this := V2ScreeningCheckListItem{}
	this.Id = id
	this.CheckType = checkType
	this.Status = status
	return &this
}

// NewV2ScreeningCheckListItemWithDefaults instantiates a new V2ScreeningCheckListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ScreeningCheckListItemWithDefaults() *V2ScreeningCheckListItem {
	this := V2ScreeningCheckListItem{}
	return &this
}

// GetId returns the Id field value
func (o *V2ScreeningCheckListItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V2ScreeningCheckListItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V2ScreeningCheckListItem) SetId(v string) {
	o.Id = v
}

// GetCheckType returns the CheckType field value
func (o *V2ScreeningCheckListItem) GetCheckType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CheckType
}

// GetCheckTypeOk returns a tuple with the CheckType field value
// and a boolean to check if the value has been set.
func (o *V2ScreeningCheckListItem) GetCheckTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CheckType, true
}

// SetCheckType sets field value
func (o *V2ScreeningCheckListItem) SetCheckType(v string) {
	o.CheckType = v
}

// GetStatus returns the Status field value
func (o *V2ScreeningCheckListItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V2ScreeningCheckListItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V2ScreeningCheckListItem) SetStatus(v string) {
	o.Status = v
}

func (o V2ScreeningCheckListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ScreeningCheckListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["check_type"] = o.CheckType
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *V2ScreeningCheckListItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"check_type",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ScreeningCheckListItem := _V2ScreeningCheckListItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ScreeningCheckListItem)

	if err != nil {
		return err
	}

	*o = V2ScreeningCheckListItem(varV2ScreeningCheckListItem)

	return err
}

type NullableV2ScreeningCheckListItem struct {
	value *V2ScreeningCheckListItem
	isSet bool
}

func (v NullableV2ScreeningCheckListItem) Get() *V2ScreeningCheckListItem {
	return v.value
}

func (v *NullableV2ScreeningCheckListItem) Set(val *V2ScreeningCheckListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ScreeningCheckListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ScreeningCheckListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ScreeningCheckListItem(val *V2ScreeningCheckListItem) *NullableV2ScreeningCheckListItem {
	return &NullableV2ScreeningCheckListItem{value: val, isSet: true}
}

func (v NullableV2ScreeningCheckListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ScreeningCheckListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


