=begin
#Pescheck API

#Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pescheck::AddOnsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AddOnsApi' do
  before do
    # run before each test
    @api_instance = Pescheck::AddOnsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddOnsApi' do
    it 'should create an instance of AddOnsApi' do
      expect(@api_instance).to be_instance_of(Pescheck::AddOnsApi)
    end
  end

  # unit tests for v2_organisations_addons_list
  # List every add-on with whether it is enabled for the organisation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :division_id Act on this division instead of the organisation the token belongs to.
  # @return [Array<OrganisationAddon>]
  describe 'v2_organisations_addons_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_organisations_addons_partial_update
  # Switch an add-on on or off. Enabling is billed monthly from today.
  # @param addon The add-on to act on.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :division_id Act on this division instead of the organisation the token belongs to.
  # @option opts [PatchedOrganisationAddonUpdate] :patched_organisation_addon_update 
  # @return [OrganisationAddonUpdateResult]
  describe 'v2_organisations_addons_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_organisations_addons_retrieve
  # Get one add-on&#39;s state for the organisation.
  # @param addon The add-on to act on.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :division_id Act on this division instead of the organisation the token belongs to.
  # @return [OrganisationAddon]
  describe 'v2_organisations_addons_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_organisations_addons_update
  # Switch an add-on on or off. Enabling is billed monthly from today.
  # @param addon The add-on to act on.
  # @param organisation_addon_update 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :division_id Act on this division instead of the organisation the token belongs to.
  # @return [OrganisationAddonUpdateResult]
  describe 'v2_organisations_addons_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
