=begin
#Pescheck API

#API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pescheck::ChecksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChecksApi' do
  before do
    # run before each test
    @api_instance = Pescheck::ChecksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChecksApi' do
    it 'should create an instance of ChecksApi' do
      expect(@api_instance).to be_instance_of(Pescheck::ChecksApi)
    end
  end

  # unit tests for v2_checks_list
  # List the check types this API supports. The list is bounded metadata about the available check types (not a paginated collection), so the response is a flat array.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :check_type Restrict the list to a single check type.
  # @return [Array<V2CheckInfo>]
  describe 'v2_checks_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_checks_retrieve
  # @param check_type 
  # @param [Hash] opts the optional parameters
  # @return [V2CheckInfo]
  describe 'v2_checks_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
