=begin
#Pescheck API

#API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pescheck::DivisionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DivisionsApi' do
  before do
    # run before each test
    @api_instance = Pescheck::DivisionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DivisionsApi' do
    it 'should create an instance of DivisionsApi' do
      expect(@api_instance).to be_instance_of(Pescheck::DivisionsApi)
    end
  end

  # unit tests for v2_organisations_divisions_create
  # Create a division (a child organisation under the current parent org). Divisions are an advanced, rarely-needed feature: create one ONLY when the user has clearly stated they want to manage a separate business unit, location, or legal entity under their account. Do NOT create a division just to organise screenings, for a single-person or single-member organisation, or without an explicit request to do so. When in doubt, ask the user to confirm before calling this tool.
  # @param division_write 
  # @param [Hash] opts the optional parameters
  # @return [DivisionWrite]
  describe 'v2_organisations_divisions_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_organisations_divisions_list
  # List method that handles both paginated and unpaginated responses and enforces the max_total_records limit (500).
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [Boolean] :paginate Enable/disable pagination. When false, max 500 records returned.
  # @return [PaginatedDivisionReadOnlyList]
  describe 'v2_organisations_divisions_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_organisations_divisions_partial_update
  # A division is a child organisation under a parent org, used only when a customer needs to manage genuinely separate business units, locations, or legal entities under one account. The vast majority of organisations operate as a single entity and need no divisions. Only top-level (parent) organisations can have divisions.
  # @param id A UUID string identifying this organisation.
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedDivisionWrite] :patched_division_write 
  # @return [DivisionWrite]
  describe 'v2_organisations_divisions_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_organisations_divisions_retrieve
  # A division is a child organisation under a parent org, used only when a customer needs to manage genuinely separate business units, locations, or legal entities under one account. The vast majority of organisations operate as a single entity and need no divisions. Only top-level (parent) organisations can have divisions.
  # @param id A UUID string identifying this organisation.
  # @param [Hash] opts the optional parameters
  # @return [DivisionReadOnly]
  describe 'v2_organisations_divisions_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_organisations_divisions_update
  # Update an existing division&#39;s contact, billing, and address details.  Override also triggers a webhook on successful PUT and PATCH requests.
  # @param id A UUID string identifying this organisation.
  # @param division_write 
  # @param [Hash] opts the optional parameters
  # @return [DivisionWrite]
  describe 'v2_organisations_divisions_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
