# coding: utf-8

"""
    Pescheck API

    Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pescheck.models.v2_screening_check_entry import V2ScreeningCheckEntry

class TestV2ScreeningCheckEntry(unittest.TestCase):
    """V2ScreeningCheckEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2ScreeningCheckEntry:
        """Test V2ScreeningCheckEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2ScreeningCheckEntry`
        """
        model = V2ScreeningCheckEntry()
        if include_optional:
            return V2ScreeningCheckEntry(
                id = '',
                profile_check_id = '',
                check_type = 'addresscheck',
                display_name = '',
                status = '',
                config = { },
                input = { },
                output = { },
                candidate_wizard_url = ''
            )
        else:
            return V2ScreeningCheckEntry(
                id = '',
                profile_check_id = '',
                check_type = 'addresscheck',
                display_name = '',
                status = '',
                config = { },
                input = { },
                output = { },
                candidate_wizard_url = '',
        )
        """

    def testV2ScreeningCheckEntry(self):
        """Test V2ScreeningCheckEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
