# coding: utf-8

"""
    Pescheck API

    Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pescheck.models.patched_v2_profile_partial_update import PatchedV2ProfilePartialUpdate

class TestPatchedV2ProfilePartialUpdate(unittest.TestCase):
    """PatchedV2ProfilePartialUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedV2ProfilePartialUpdate:
        """Test PatchedV2ProfilePartialUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedV2ProfilePartialUpdate`
        """
        model = PatchedV2ProfilePartialUpdate()
        if include_optional:
            return PatchedV2ProfilePartialUpdate(
                name = '',
                description = ''
            )
        else:
            return PatchedV2ProfilePartialUpdate(
        )
        """

    def testPatchedV2ProfilePartialUpdate(self):
        """Test PatchedV2ProfilePartialUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
