/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V2CheckField model module.
 * @module model/V2CheckField
 * @version 0.1.0
 */
class V2CheckField {
    /**
     * Constructs a new <code>V2CheckField</code>.
     * One config or input field a check accepts via the API.
     * @alias module:model/V2CheckField
     */
    constructor() { 
        
        V2CheckField.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V2CheckField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V2CheckField} obj Optional instance to populate.
     * @return {module:model/V2CheckField} The populated <code>V2CheckField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2CheckField();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
            if (data.hasOwnProperty('choices')) {
                obj['choices'] = ApiClient.convertToType(data['choices'], ['String']);
            }
            if (data.hasOwnProperty('help_text')) {
                obj['help_text'] = ApiClient.convertToType(data['help_text'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V2CheckField</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V2CheckField</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['choices'])) {
            throw new Error("Expected the field `choices` to be an array in the JSON data but got " + data['choices']);
        }
        // ensure the json data is a string
        if (data['help_text'] && !(typeof data['help_text'] === 'string' || data['help_text'] instanceof String)) {
            throw new Error("Expected the field `help_text` to be a primitive type in the JSON string but got " + data['help_text']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
V2CheckField.prototype['name'] = undefined;

/**
 * \"string\" | \"integer\" | \"number\" | \"boolean\" | \"array\" | \"object\"
 * @member {String} type
 */
V2CheckField.prototype['type'] = undefined;

/**
 * Whether the request body must include this field.
 * @member {Boolean} required
 */
V2CheckField.prototype['required'] = undefined;

/**
 * Allowed values, or null if the field isn't constrained to a set.
 * @member {Array.<String>} choices
 */
V2CheckField.prototype['choices'] = undefined;

/**
 * @member {String} help_text
 */
V2CheckField.prototype['help_text'] = undefined;






export default V2CheckField;

