/**
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V2Money from './V2Money';
import V2ProfileCheckEntry from './V2ProfileCheckEntry';

/**
 * The V2ProfileDetail model module.
 * @module model/V2ProfileDetail
 * @version 2.0.0
 */
class V2ProfileDetail {
    /**
     * Constructs a new <code>V2ProfileDetail</code>.
     * @alias module:model/V2ProfileDetail
     * @param id {String} 
     * @param name {String} 
     * @param description {String} 
     * @param checks {Array.<module:model/V2ProfileCheckEntry>} 
     * @param totalPrice {module:model/V2Money} 
     * @param supportedCountriesOfWork {Array.<String>} 
     * @param supportedCountriesOfResidence {Array.<String>} 
     * @param candidateFields {Array.<Object>} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, name, description, checks, totalPrice, supportedCountriesOfWork, supportedCountriesOfResidence, candidateFields, createdAt, updatedAt) { 
        
        V2ProfileDetail.initialize(this, id, name, description, checks, totalPrice, supportedCountriesOfWork, supportedCountriesOfResidence, candidateFields, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, description, checks, totalPrice, supportedCountriesOfWork, supportedCountriesOfResidence, candidateFields, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['description'] = description;
        obj['checks'] = checks;
        obj['total_price'] = totalPrice;
        obj['supported_countries_of_work'] = supportedCountriesOfWork;
        obj['supported_countries_of_residence'] = supportedCountriesOfResidence;
        obj['candidate_fields'] = candidateFields;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>V2ProfileDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V2ProfileDetail} obj Optional instance to populate.
     * @return {module:model/V2ProfileDetail} The populated <code>V2ProfileDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2ProfileDetail();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('is_custom')) {
                obj['is_custom'] = ApiClient.convertToType(data['is_custom'], 'Boolean');
            }
            if (data.hasOwnProperty('checks')) {
                obj['checks'] = ApiClient.convertToType(data['checks'], [V2ProfileCheckEntry]);
            }
            if (data.hasOwnProperty('total_price')) {
                obj['total_price'] = ApiClient.convertToType(data['total_price'], V2Money);
            }
            if (data.hasOwnProperty('supported_countries_of_work')) {
                obj['supported_countries_of_work'] = ApiClient.convertToType(data['supported_countries_of_work'], ['String']);
            }
            if (data.hasOwnProperty('supported_countries_of_residence')) {
                obj['supported_countries_of_residence'] = ApiClient.convertToType(data['supported_countries_of_residence'], ['String']);
            }
            if (data.hasOwnProperty('candidate_fields')) {
                obj['candidate_fields'] = ApiClient.convertToType(data['candidate_fields'], [Object]);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V2ProfileDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V2ProfileDetail</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V2ProfileDetail.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['checks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['checks'])) {
                throw new Error("Expected the field `checks` to be an array in the JSON data but got " + data['checks']);
            }
            // validate the optional field `checks` (array)
            for (const item of data['checks']) {
                V2ProfileCheckEntry.validateJSON(item);
            };
        }
        // validate the optional field `total_price`
        if (data['total_price']) { // data not null
          V2Money.validateJSON(data['total_price']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['supported_countries_of_work'])) {
            throw new Error("Expected the field `supported_countries_of_work` to be an array in the JSON data but got " + data['supported_countries_of_work']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['supported_countries_of_residence'])) {
            throw new Error("Expected the field `supported_countries_of_residence` to be an array in the JSON data but got " + data['supported_countries_of_residence']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['candidate_fields'])) {
            throw new Error("Expected the field `candidate_fields` to be an array in the JSON data but got " + data['candidate_fields']);
        }

        return true;
    }


}

V2ProfileDetail.RequiredProperties = ["id", "name", "description", "checks", "total_price", "supported_countries_of_work", "supported_countries_of_residence", "candidate_fields", "created_at", "updated_at"];

/**
 * @member {String} id
 */
V2ProfileDetail.prototype['id'] = undefined;

/**
 * @member {String} name
 */
V2ProfileDetail.prototype['name'] = undefined;

/**
 * @member {String} description
 */
V2ProfileDetail.prototype['description'] = undefined;

/**
 * @member {Boolean} is_custom
 */
V2ProfileDetail.prototype['is_custom'] = undefined;

/**
 * @member {Array.<module:model/V2ProfileCheckEntry>} checks
 */
V2ProfileDetail.prototype['checks'] = undefined;

/**
 * @member {module:model/V2Money} total_price
 */
V2ProfileDetail.prototype['total_price'] = undefined;

/**
 * @member {Array.<String>} supported_countries_of_work
 */
V2ProfileDetail.prototype['supported_countries_of_work'] = undefined;

/**
 * @member {Array.<String>} supported_countries_of_residence
 */
V2ProfileDetail.prototype['supported_countries_of_residence'] = undefined;

/**
 * @member {Array.<Object>} candidate_fields
 */
V2ProfileDetail.prototype['candidate_fields'] = undefined;

/**
 * @member {Date} created_at
 */
V2ProfileDetail.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
V2ProfileDetail.prototype['updated_at'] = undefined;






export default V2ProfileDetail;

