/* tslint:disable */
/* eslint-disable */
/**
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2ProfileListItem } from './V2ProfileListItem';
import {
    V2ProfileListItemFromJSON,
    V2ProfileListItemFromJSONTyped,
    V2ProfileListItemToJSON,
    V2ProfileListItemToJSONTyped,
} from './V2ProfileListItem';

/**
 * 
 * @export
 * @interface PaginatedV2ProfileListItemList
 */
export interface PaginatedV2ProfileListItemList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedV2ProfileListItemList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedV2ProfileListItemList
     */
    next: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedV2ProfileListItemList
     */
    previous: string | null;
    /**
     * 
     * @type {Array<V2ProfileListItem>}
     * @memberof PaginatedV2ProfileListItemList
     */
    results: Array<V2ProfileListItem>;
}

/**
 * Check if a given object implements the PaginatedV2ProfileListItemList interface.
 */
export function instanceOfPaginatedV2ProfileListItemList(value: any): value is PaginatedV2ProfileListItemList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedV2ProfileListItemListFromJSON(json: any): PaginatedV2ProfileListItemList {
    return PaginatedV2ProfileListItemListFromJSONTyped(json, false);
}

export function PaginatedV2ProfileListItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedV2ProfileListItemList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(V2ProfileListItemFromJSON)),
    };
}

export function PaginatedV2ProfileListItemListToJSON(json: any): PaginatedV2ProfileListItemList {
    return PaginatedV2ProfileListItemListToJSONTyped(json, false);
}

export function PaginatedV2ProfileListItemListToJSONTyped(value?: PaginatedV2ProfileListItemList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(V2ProfileListItemToJSON)),
    };
}

