/* tslint:disable */
/* eslint-disable */
/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DivisionReadOnly } from './DivisionReadOnly';
import {
    DivisionReadOnlyFromJSON,
    DivisionReadOnlyFromJSONTyped,
    DivisionReadOnlyToJSON,
    DivisionReadOnlyToJSONTyped,
} from './DivisionReadOnly';

/**
 * 
 * @export
 * @interface PaginatedDivisionReadOnlyList
 */
export interface PaginatedDivisionReadOnlyList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDivisionReadOnlyList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDivisionReadOnlyList
     */
    next: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDivisionReadOnlyList
     */
    previous: string | null;
    /**
     * 
     * @type {Array<DivisionReadOnly>}
     * @memberof PaginatedDivisionReadOnlyList
     */
    results: Array<DivisionReadOnly>;
}

/**
 * Check if a given object implements the PaginatedDivisionReadOnlyList interface.
 */
export function instanceOfPaginatedDivisionReadOnlyList(value: any): value is PaginatedDivisionReadOnlyList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedDivisionReadOnlyListFromJSON(json: any): PaginatedDivisionReadOnlyList {
    return PaginatedDivisionReadOnlyListFromJSONTyped(json, false);
}

export function PaginatedDivisionReadOnlyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDivisionReadOnlyList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(DivisionReadOnlyFromJSON)),
    };
}

export function PaginatedDivisionReadOnlyListToJSON(json: any): PaginatedDivisionReadOnlyList {
    return PaginatedDivisionReadOnlyListToJSONTyped(json, false);
}

export function PaginatedDivisionReadOnlyListToJSONTyped(value?: PaginatedDivisionReadOnlyList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(DivisionReadOnlyToJSON)),
    };
}

