/* tslint:disable */
/* eslint-disable */
/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One config or input field a check accepts via the API.
 * @export
 * @interface V2CheckField
 */
export interface V2CheckField {
    /**
     * 
     * @type {string}
     * @memberof V2CheckField
     */
    readonly name: string;
    /**
     * "string" | "integer" | "number" | "boolean" | "array" | "object"
     * @type {string}
     * @memberof V2CheckField
     */
    readonly type: string;
    /**
     * Whether the request body must include this field.
     * @type {boolean}
     * @memberof V2CheckField
     */
    readonly required: boolean;
    /**
     * Allowed values, or null if the field isn't constrained to a set. Each choice has "value" (what to send), "label" (human-readable), and possibly check-specific extras such as "description".
     * @type {Array<{ [key: string]: any; }>}
     * @memberof V2CheckField
     */
    readonly choices: Array<{ [key: string]: any; }> | null;
    /**
     * 
     * @type {string}
     * @memberof V2CheckField
     */
    readonly helpText: string | null;
}

/**
 * Check if a given object implements the V2CheckField interface.
 */
export function instanceOfV2CheckField(value: any): value is V2CheckField {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('required' in value) || value['required'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    if ((!('helpText' in value) && !('help_text' in value)) || (value['helpText'] === undefined && value['help_text'] === undefined)) return false;
    return true;
}

export function V2CheckFieldFromJSON(json: any): V2CheckField {
    return V2CheckFieldFromJSONTyped(json, false);
}

export function V2CheckFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2CheckField {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'required': json['required'],
        'choices': json['choices'] == null ? null : json['choices'],
        'helpText': json['help_text'],
    };
}

export function V2CheckFieldToJSON(json: any): V2CheckField {
    return V2CheckFieldToJSONTyped(json, false);
}

export function V2CheckFieldToJSONTyped(value?: Omit<V2CheckField, 'name'|'type'|'required'|'choices'|'help_text'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

