/* tslint:disable */
/* eslint-disable */
/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2ProfileCheckEntry } from './V2ProfileCheckEntry';
import {
    V2ProfileCheckEntryFromJSON,
    V2ProfileCheckEntryFromJSONTyped,
    V2ProfileCheckEntryToJSON,
    V2ProfileCheckEntryToJSONTyped,
} from './V2ProfileCheckEntry';
import type { V2Money } from './V2Money';
import {
    V2MoneyFromJSON,
    V2MoneyFromJSONTyped,
    V2MoneyToJSON,
    V2MoneyToJSONTyped,
} from './V2Money';

/**
 * 
 * @export
 * @interface V2ProfileDetail
 */
export interface V2ProfileDetail {
    /**
     * 
     * @type {string}
     * @memberof V2ProfileDetail
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof V2ProfileDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V2ProfileDetail
     */
    description: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof V2ProfileDetail
     */
    isCustom?: boolean;
    /**
     * 
     * @type {Array<V2ProfileCheckEntry>}
     * @memberof V2ProfileDetail
     */
    readonly checks?: Array<V2ProfileCheckEntry>;
    /**
     * 
     * @type {V2Money}
     * @memberof V2ProfileDetail
     */
    readonly totalPrice?: V2Money;
    /**
     * 
     * @type {Array<string>}
     * @memberof V2ProfileDetail
     */
    readonly supportedCountriesOfWork?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V2ProfileDetail
     */
    readonly supportedCountriesOfResidence?: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof V2ProfileDetail
     */
    readonly candidateFields?: Array<object>;
    /**
     * 
     * @type {Date}
     * @memberof V2ProfileDetail
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V2ProfileDetail
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the V2ProfileDetail interface.
 */
export function instanceOfV2ProfileDetail(value: any): value is V2ProfileDetail {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function V2ProfileDetailFromJSON(json: any): V2ProfileDetail {
    return V2ProfileDetailFromJSONTyped(json, false);
}

export function V2ProfileDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2ProfileDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'],
        'isCustom': json['is_custom'] == null ? undefined : json['is_custom'],
        'checks': json['checks'] == null ? undefined : ((json['checks'] as Array<any>).map(V2ProfileCheckEntryFromJSON)),
        'totalPrice': json['total_price'] == null ? undefined : V2MoneyFromJSON(json['total_price']),
        'supportedCountriesOfWork': json['supported_countries_of_work'] == null ? undefined : json['supported_countries_of_work'],
        'supportedCountriesOfResidence': json['supported_countries_of_residence'] == null ? undefined : json['supported_countries_of_residence'],
        'candidateFields': json['candidate_fields'] == null ? undefined : json['candidate_fields'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function V2ProfileDetailToJSON(json: any): V2ProfileDetail {
    return V2ProfileDetailToJSONTyped(json, false);
}

export function V2ProfileDetailToJSONTyped(value?: Omit<V2ProfileDetail, 'id'|'checks'|'total_price'|'supported_countries_of_work'|'supported_countries_of_residence'|'candidate_fields'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'is_custom': value['isCustom'],
    };
}

