/* tslint:disable */
/* eslint-disable */
/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A note to record on the screening at creation. Scope it to a specific check with
 * `profile_check_id` (links the note to the Check spawned from that ProfileCheck) or to
 * a `check_type`; `profile_check_id` wins when both are given. With neither, the note is
 * recorded against the screening with no check (check_type 'other').
 * @export
 * @interface V2ScreeningNoteInput
 */
export interface V2ScreeningNoteInput {
    /**
     * 
     * @type {string}
     * @memberof V2ScreeningNoteInput
     */
    note: string;
    /**
     * Links the note to the Check spawned from this ProfileCheck. Wins over check_type.
     * @type {string}
     * @memberof V2ScreeningNoteInput
     */
    profileCheckId?: string | null;
    /**
     * Scope the note to a check type. Ignored when profile_check_id is given.
     * 
     * * `addresscheck` - addresscheck
     * * `adversemedia2check` - adversemedia2check
     * * `adversemediacheck` - adversemediacheck
     * * `bigcheck` - bigcheck
     * * `criminalrecordscheck` - criminalrecordscheck
     * * `criminalrecordsuploadcheck` - criminalrecordsuploadcheck
     * * `customintegritycheck` - customintegritycheck
     * * `cvcheck` - cvcheck
     * * `edrcheck` - edrcheck
     * * `focumcheck` - focumcheck
     * * `id2check` - id2check
     * * `idcheck` - idcheck
     * * `integritycheck` - integritycheck
     * * `openhealthcarecheck` - openhealthcarecheck
     * * `permissioncheck` - permissioncheck
     * * `pescheckadversemediacheck` - pescheckadversemediacheck
     * * `qualificationcheck` - qualificationcheck
     * * `righttoworkcheck` - righttoworkcheck
     * * `vogcheck` - vogcheck
     * * `watchlist2check` - watchlist2check
     * * `watchlistcheck` - watchlistcheck
     * * `workreferencecheck` - workreferencecheck
     * * `worldwidecreditcheck` - worldwidecreditcheck
     * @type {V2ScreeningNoteInputCheckTypeEnum}
     * @memberof V2ScreeningNoteInput
     */
    checkType?: V2ScreeningNoteInputCheckTypeEnum;
}


/**
 * @export
 */
export const V2ScreeningNoteInputCheckTypeEnum = {
    Addresscheck: 'addresscheck',
    Adversemedia2check: 'adversemedia2check',
    Adversemediacheck: 'adversemediacheck',
    Bigcheck: 'bigcheck',
    Criminalrecordscheck: 'criminalrecordscheck',
    Criminalrecordsuploadcheck: 'criminalrecordsuploadcheck',
    Customintegritycheck: 'customintegritycheck',
    Cvcheck: 'cvcheck',
    Edrcheck: 'edrcheck',
    Focumcheck: 'focumcheck',
    Id2check: 'id2check',
    Idcheck: 'idcheck',
    Integritycheck: 'integritycheck',
    Openhealthcarecheck: 'openhealthcarecheck',
    Permissioncheck: 'permissioncheck',
    Pescheckadversemediacheck: 'pescheckadversemediacheck',
    Qualificationcheck: 'qualificationcheck',
    Righttoworkcheck: 'righttoworkcheck',
    Vogcheck: 'vogcheck',
    Watchlist2check: 'watchlist2check',
    Watchlistcheck: 'watchlistcheck',
    Workreferencecheck: 'workreferencecheck',
    Worldwidecreditcheck: 'worldwidecreditcheck',
    Empty: ''
} as const;
export type V2ScreeningNoteInputCheckTypeEnum = typeof V2ScreeningNoteInputCheckTypeEnum[keyof typeof V2ScreeningNoteInputCheckTypeEnum];


/**
 * Check if a given object implements the V2ScreeningNoteInput interface.
 */
export function instanceOfV2ScreeningNoteInput(value: any): value is V2ScreeningNoteInput {
    if (!('note' in value) || value['note'] === undefined) return false;
    return true;
}

export function V2ScreeningNoteInputFromJSON(json: any): V2ScreeningNoteInput {
    return V2ScreeningNoteInputFromJSONTyped(json, false);
}

export function V2ScreeningNoteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2ScreeningNoteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'],
        'profileCheckId': json['profile_check_id'] == null ? undefined : json['profile_check_id'],
        'checkType': json['check_type'] == null ? undefined : json['check_type'],
    };
}

export function V2ScreeningNoteInputToJSON(json: any): V2ScreeningNoteInput {
    return V2ScreeningNoteInputToJSONTyped(json, false);
}

export function V2ScreeningNoteInputToJSONTyped(value?: V2ScreeningNoteInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'profile_check_id': value['profileCheckId'],
        'check_type': value['checkType'],
    };
}

