/*
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.pescheck.client.api;

import io.pescheck.client.ApiException;
import io.pescheck.client.model.VerifyWebhook;
import io.pescheck.client.model.Webhook;
import io.pescheck.client.model.WebhookResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhooksApi
 */
@Disabled
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    /**
     * Create webhook for event notifications.          **Authentication Notes:**         - OAuth2: Organization is automatically determined from the OAuth application         - If your OAuth app has no organization set, pass it via &#x60;X-Organization-Id&#x60; header or &#x60;organization_id&#x60; query parameter          **Valid Events:**         - &#x60;check.started&#x60; - Check has been initiated         - &#x60;check.completed&#x60; - Check has been completed successfully         - &#x60;check.failed&#x60; - Check has failed         - &#x60;screening.created&#x60; - New screening has been created         - &#x60;screening.completed&#x60; - Screening has been completed         - &#x60;screening.archived&#x60; - Screening has been archived         - &#x60;package.created&#x60; - New package has been created         - &#x60;package.updated&#x60; - Package has been updated         - &#x60;division.created&#x60; - New division has been created         - &#x60;division.updated&#x60; - Division has been updated          Limited to 5 webhooks per organization/division.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWebhook2Test() throws ApiException {
        Webhook webhook = null;
        String xOrganizationId = null;
        String organizationId = null;
        WebhookResponse response = api.createWebhook2(webhook, xOrganizationId, organizationId);
        // TODO: test validations
    }

    /**
     * Delete a webhook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteWebhook2Test() throws ApiException {
        String webhookId = null;
        api.deleteWebhook2(webhookId);
        // TODO: test validations
    }

    /**
     * List webhooks for the organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listWebhooks2Test() throws ApiException {
        List<WebhookResponse> response = api.listWebhooks2();
        // TODO: test validations
    }

    /**
     * Verify webhook ownership
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyWebhook2Test() throws ApiException {
        String webhookId = null;
        VerifyWebhook verifyWebhook = null;
        api.verifyWebhook2(webhookId, verifyWebhook);
        // TODO: test validations
    }

}
