generatorName: javascript
inputSpec: spec/openapi.v2.yaml
outputDir: clients/javascript
gitHost: github.com
gitUserId: pescheckit
gitRepoId: pescheck-clients
additionalProperties:
  projectName: "@pescheckit/api-client-js"
  moduleName: PescheckApi
  projectVersion: 0.0.1
  usePromises: "true"
  useES6: "true"
