generatorName: python
inputSpec: spec/openapi.v2.yaml
outputDir: clients/python
gitHost: github.com
gitUserId: pescheckit
gitRepoId: pescheck-clients
additionalProperties:
  packageName: pescheck
  projectName: pescheck
  packageVersion: 0.0.4
  packageUrl: https://pescheck.io
  library: urllib3
  generateSourceCodeOnly: "false"
