generatorName: ruby
inputSpec: spec/openapi.v2.yaml
outputDir: clients/ruby
gitHost: github.com
gitUserId: pescheckit
gitRepoId: pescheck-clients
library: faraday
additionalProperties:
  gemName: pescheck-client
  moduleName: Pescheck
  gemVersion: 0.1.0
  gemHomepage: https://pescheck.io
  gemSummary: Official Ruby client for the Pescheck API
  gemAuthor: Pescheck
