generatorName: typescript-fetch
inputSpec: spec/openapi.v2.yaml
outputDir: clients/typescript
gitHost: github.com
gitUserId: pescheckit
gitRepoId: pescheck-clients
additionalProperties:
  npmName: "@pescheckit/pescheck-client"
  npmVersion: 0.1.0
  supportsES6: "true"
  typescriptThreePlus: "true"
  withInterfaces: "true"
