/**
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DivisionReadOnly.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DivisionReadOnly_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DivisionReadOnly_H_

#include <boost/optional.hpp>

#include "PescheckApi/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  DivisionReadOnly
    : public ModelBase
{
public:
    DivisionReadOnly();
    virtual ~DivisionReadOnly();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DivisionReadOnly members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getParent() const;
    bool parentIsSet() const;
    void unsetParent();
    void setParent(const utility::string_t& value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreated_at();
    void setCreatedAt(const utility::datetime& value);

    utility::datetime getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdated_at();
    void setUpdatedAt(const utility::datetime& value);

    utility::string_t getCity() const;
    bool cityIsSet() const;
    void unsetCity();
    void setCity(const utility::string_t& value);

    utility::string_t getAddress() const;
    bool addressIsSet() const;
    void unsetAddress();
    void setAddress(const utility::string_t& value);

    utility::string_t getPostal() const;
    bool postalIsSet() const;
    void unsetPostal();
    void setPostal(const utility::string_t& value);

    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(const utility::string_t& value);

    utility::string_t getContactName() const;
    bool contactNameIsSet() const;
    void unsetContact_name();
    void setContactName(const utility::string_t& value);

    utility::string_t getContactEmail() const;
    bool contactEmailIsSet() const;
    void unsetContact_email();
    void setContactEmail(const utility::string_t& value);

    utility::string_t getInvoiceEmail() const;
    bool invoiceEmailIsSet() const;
    void unsetInvoice_email();
    void setInvoiceEmail(const utility::string_t& value);

    bool isUseParentOnEmail() const;
    bool useParentOnEmailIsSet() const;
    void unsetUse_parent_on_email();
    void setUseParentOnEmail(bool value);

    bool isUseParentOnBilling() const;
    bool useParentOnBillingIsSet() const;
    void unsetUse_parent_on_billing();
    void setUseParentOnBilling(bool value);

    bool isUseParentOnReport() const;
    bool useParentOnReportIsSet() const;
    void unsetUse_parent_on_report();
    void setUseParentOnReport(bool value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    boost::optional<utility::string_t> m_Name;

    utility::string_t m_Parent;
    bool m_ParentIsSet;

    utility::datetime m_Created_at;
    bool m_Created_atIsSet;

    utility::datetime m_Updated_at;
    bool m_Updated_atIsSet;

    boost::optional<utility::string_t> m_City;

    boost::optional<utility::string_t> m_Address;

    boost::optional<utility::string_t> m_Postal;

    boost::optional<utility::string_t> m_Phone;

    boost::optional<utility::string_t> m_Contact_name;

    boost::optional<utility::string_t> m_Contact_email;

    boost::optional<utility::string_t> m_Invoice_email;

    bool m_Use_parent_on_email;
    bool m_Use_parent_on_emailIsSet;

    bool m_Use_parent_on_billing;
    bool m_Use_parent_on_billingIsSet;

    bool m_Use_parent_on_report;
    bool m_Use_parent_on_reportIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DivisionReadOnly_H_ */
