/**
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PaginatedDivisionReadOnlyList.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedDivisionReadOnlyList_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedDivisionReadOnlyList_H_

#include <boost/optional.hpp>

#include "PescheckApi/ModelBase.h"

#include "PescheckApi/model/DivisionReadOnly.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class DivisionReadOnly;


class  PaginatedDivisionReadOnlyList
    : public ModelBase
{
public:
    PaginatedDivisionReadOnlyList();
    virtual ~PaginatedDivisionReadOnlyList();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// PaginatedDivisionReadOnlyList members


    int32_t getCount() const;
    bool countIsSet() const;
    void unsetCount();
    void setCount(int32_t value);

    utility::string_t getNext() const;
    bool nextIsSet() const;
    void unsetNext();
    void setNext(const utility::string_t& value);

    utility::string_t getPrevious() const;
    bool previousIsSet() const;
    void unsetPrevious();
    void setPrevious(const utility::string_t& value);

    std::vector<std::shared_ptr<DivisionReadOnly>> getResults() const;
    bool resultsIsSet() const;
    void unsetResults();
    void setResults(const std::vector<std::shared_ptr<DivisionReadOnly>>& value);


protected:
    int32_t m_Count;
    bool m_CountIsSet;

    boost::optional<utility::string_t> m_Next;

    boost::optional<utility::string_t> m_Previous;

    std::vector<std::shared_ptr<DivisionReadOnly>> m_Results;
    bool m_ResultsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedDivisionReadOnlyList_H_ */
