/**
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * V2CheckField.h
 *
 * One config or input field a check accepts via the API.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_V2CheckField_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_V2CheckField_H_

#include <boost/optional.hpp>

#include "PescheckApi/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// One config or input field a check accepts via the API.
/// </summary>
class  V2CheckField
    : public ModelBase
{
public:
    V2CheckField();
    virtual ~V2CheckField();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// V2CheckField members


    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    /// <summary>
    /// \&quot;string\&quot; | \&quot;integer\&quot; | \&quot;number\&quot; | \&quot;boolean\&quot; | \&quot;array\&quot; | \&quot;object\&quot;
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const utility::string_t& value);

    /// <summary>
    /// Whether the request body must include this field.
    /// </summary>
    bool isRequired() const;
    bool requiredIsSet() const;
    void unsetRequired();
    void setRequired(bool value);

    /// <summary>
    /// Allowed values, or null if the field isn&#39;t constrained to a set.
    /// </summary>
    std::vector<utility::string_t> getChoices() const;
    bool choicesIsSet() const;
    void unsetChoices();
    void setChoices(const std::vector<utility::string_t>& value);

    utility::string_t getHelpText() const;
    bool helpTextIsSet() const;
    void unsetHelp_text();
    void setHelpText(const utility::string_t& value);


protected:
    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Type;
    bool m_TypeIsSet;

    bool m_Required;
    bool m_RequiredIsSet;

    boost::optional<std::vector<utility::string_t>> m_Choices;

    boost::optional<utility::string_t> m_Help_text;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_V2CheckField_H_ */
