/**
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * V2CheckInfo.h
 *
 * Everything a client needs to know to use a check type via the API.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_V2CheckInfo_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_V2CheckInfo_H_

#include <boost/optional.hpp>

#include "PescheckApi/ModelBase.h"

#include "PescheckApi/model/V2Money.h"
#include <cpprest/details/basic_types.h>
#include <vector>
#include "PescheckApi/model/V2CheckField.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class V2Money;
class V2CheckField;


/// <summary>
/// Everything a client needs to know to use a check type via the API.
/// </summary>
class  V2CheckInfo
    : public ModelBase
{
public:
    V2CheckInfo();
    virtual ~V2CheckInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// V2CheckInfo members


    utility::string_t getCheckType() const;
    bool checkTypeIsSet() const;
    void unsetCheck_type();
    void setCheckType(const utility::string_t& value);

    utility::string_t getDisplayName() const;
    bool displayNameIsSet() const;
    void unsetDisplay_name();
    void setDisplayName(const utility::string_t& value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    bool isHasConfig() const;
    bool hasConfigIsSet() const;
    void unsetHas_config();
    void setHasConfig(bool value);

    /// <summary>
    /// True for checks added automatically (e.g. as a dependency) - clients neither add nor configure these.
    /// </summary>
    bool isIsSystemManaged() const;
    bool isSystemManagedIsSet() const;
    void unsetIs_system_managed();
    void setIsSystemManaged(bool value);

    /// <summary>
    /// Other check types this check pulls in automatically when added.
    /// </summary>
    std::vector<utility::string_t> getRequiresChecks() const;
    bool requiresChecksIsSet() const;
    void unsetRequires_checks();
    void setRequiresChecks(const std::vector<utility::string_t>& value);

    std::vector<utility::string_t> getSupportedCountriesOfWork() const;
    bool supportedCountriesOfWorkIsSet() const;
    void unsetSupported_countries_of_work();
    void setSupportedCountriesOfWork(const std::vector<utility::string_t>& value);

    std::vector<utility::string_t> getSupportedCountriesOfResidence() const;
    bool supportedCountriesOfResidenceIsSet() const;
    void unsetSupported_countries_of_residence();
    void setSupportedCountriesOfResidence(const std::vector<utility::string_t>& value);

    std::shared_ptr<V2Money> getDefaultPrice() const;
    bool defaultPriceIsSet() const;
    void unsetDefault_price();
    void setDefaultPrice(const std::shared_ptr<V2Money>& value);

    std::vector<std::shared_ptr<V2CheckField>> getConfigFields() const;
    bool configFieldsIsSet() const;
    void unsetConfig_fields();
    void setConfigFields(const std::vector<std::shared_ptr<V2CheckField>>& value);

    std::vector<std::shared_ptr<V2CheckField>> getInputFields() const;
    bool inputFieldsIsSet() const;
    void unsetInput_fields();
    void setInputFields(const std::vector<std::shared_ptr<V2CheckField>>& value);

    /// <summary>
    /// Screening-level candidate facts this check needs (name, email, sometimes date of birth, etc.).
    /// </summary>
    std::vector<std::shared_ptr<V2CheckField>> getCandidateFields() const;
    bool candidateFieldsIsSet() const;
    void unsetCandidate_fields();
    void setCandidateFields(const std::vector<std::shared_ptr<V2CheckField>>& value);


protected:
    utility::string_t m_Check_type;
    bool m_Check_typeIsSet;

    utility::string_t m_Display_name;
    bool m_Display_nameIsSet;

    boost::optional<utility::string_t> m_Description;

    bool m_Has_config;
    bool m_Has_configIsSet;

    bool m_Is_system_managed;
    bool m_Is_system_managedIsSet;

    std::vector<utility::string_t> m_Requires_checks;
    bool m_Requires_checksIsSet;

    std::vector<utility::string_t> m_Supported_countries_of_work;
    bool m_Supported_countries_of_workIsSet;

    std::vector<utility::string_t> m_Supported_countries_of_residence;
    bool m_Supported_countries_of_residenceIsSet;

    boost::optional<std::shared_ptr<V2Money>> m_Default_price;

    std::vector<std::shared_ptr<V2CheckField>> m_Config_fields;
    bool m_Config_fieldsIsSet;

    std::vector<std::shared_ptr<V2CheckField>> m_Input_fields;
    bool m_Input_fieldsIsSet;

    std::vector<std::shared_ptr<V2CheckField>> m_Candidate_fields;
    bool m_Candidate_fieldsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_V2CheckInfo_H_ */
