/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * V2ScreeningCreate.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_V2ScreeningCreate_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_V2ScreeningCreate_H_

#include <boost/optional.hpp>

#include "PescheckApi/ModelBase.h"

#include "PescheckApi/model/V2Candidate.h"
#include "PescheckApi/model/V2ScreeningCheck.h"
#include <cpprest/details/basic_types.h>
#include "PescheckApi/model/V2ScreeningNoteInput.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class V2Candidate;
class V2ScreeningCheck;
class V2ScreeningNoteInput;


class  V2ScreeningCreate
    : public ModelBase
{
public:
    V2ScreeningCreate();
    virtual ~V2ScreeningCreate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// V2ScreeningCreate members


    utility::string_t getProfileId() const;
    bool profileIdIsSet() const;
    void unsetProfile_id();
    void setProfileId(const utility::string_t& value);

    std::shared_ptr<V2Candidate> getCandidate() const;
    bool candidateIsSet() const;
    void unsetCandidate();
    void setCandidate(const std::shared_ptr<V2Candidate>& value);

    std::vector<std::shared_ptr<V2ScreeningCheck>> getChecks() const;
    bool checksIsSet() const;
    void unsetChecks();
    void setChecks(const std::vector<std::shared_ptr<V2ScreeningCheck>>& value);

    std::vector<std::shared_ptr<V2ScreeningNoteInput>> getScreeningNotes() const;
    bool screeningNotesIsSet() const;
    void unsetScreening_notes();
    void setScreeningNotes(const std::vector<std::shared_ptr<V2ScreeningNoteInput>>& value);


protected:
    utility::string_t m_Profile_id;
    bool m_Profile_idIsSet;

    std::shared_ptr<V2Candidate> m_Candidate;
    bool m_CandidateIsSet;

    std::vector<std::shared_ptr<V2ScreeningCheck>> m_Checks;
    bool m_ChecksIsSet;

    std::vector<std::shared_ptr<V2ScreeningNoteInput>> m_Screening_notes;
    bool m_Screening_notesIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_V2ScreeningCreate_H_ */
