/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * V2ScreeningNoteInput.h
 *
 * A note to record on the screening at creation. Scope it to a specific check with &#x60;profile_check_id&#x60; (links the note to the Check spawned from that ProfileCheck) or to a &#x60;check_type&#x60;; &#x60;profile_check_id&#x60; wins when both are given. With neither, the note is recorded against the screening with no check (check_type &#39;other&#39;).
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_V2ScreeningNoteInput_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_V2ScreeningNoteInput_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "PescheckApi/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// A note to record on the screening at creation. Scope it to a specific check with &#x60;profile_check_id&#x60; (links the note to the Check spawned from that ProfileCheck) or to a &#x60;check_type&#x60;; &#x60;profile_check_id&#x60; wins when both are given. With neither, the note is recorded against the screening with no check (check_type &#39;other&#39;).
/// </summary>
class  V2ScreeningNoteInput
    : public ModelBase
{
public:
    V2ScreeningNoteInput();
    virtual ~V2ScreeningNoteInput();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// V2ScreeningNoteInput members

    enum class Check_typeEnum
    {
        ADDRESSCHECK,
        ADVERSEMEDIA2CHECK,
        ADVERSEMEDIACHECK,
        BIGCHECK,
        CRIMINALRECORDSCHECK,
        CRIMINALRECORDSUPLOADCHECK,
        CUSTOMINTEGRITYCHECK,
        CVCHECK,
        EDRCHECK,
        FOCUMCHECK,
        ID2CHECK,
        IDCHECK,
        INTEGRITYCHECK,
        OPENHEALTHCARECHECK,
        PERMISSIONCHECK,
        PESCHECKADVERSEMEDIACHECK,
        QUALIFICATIONCHECK,
        RIGHTTOWORKCHECK,
        VOGCHECK,
        WATCHLIST2CHECK,
        WATCHLISTCHECK,
        WORKREFERENCECHECK,
        WORLDWIDECREDITCHECK,
        EMPTY,
    };
    /// <summary>
    /// Scope the note to a check type. Ignored when profile_check_id is given.  * &#x60;addresscheck&#x60; - addresscheck * &#x60;adversemedia2check&#x60; - adversemedia2check * &#x60;adversemediacheck&#x60; - adversemediacheck * &#x60;bigcheck&#x60; - bigcheck * &#x60;criminalrecordscheck&#x60; - criminalrecordscheck * &#x60;criminalrecordsuploadcheck&#x60; - criminalrecordsuploadcheck * &#x60;customintegritycheck&#x60; - customintegritycheck * &#x60;cvcheck&#x60; - cvcheck * &#x60;edrcheck&#x60; - edrcheck * &#x60;focumcheck&#x60; - focumcheck * &#x60;id2check&#x60; - id2check * &#x60;idcheck&#x60; - idcheck * &#x60;integritycheck&#x60; - integritycheck * &#x60;openhealthcarecheck&#x60; - openhealthcarecheck * &#x60;permissioncheck&#x60; - permissioncheck * &#x60;pescheckadversemediacheck&#x60; - pescheckadversemediacheck * &#x60;qualificationcheck&#x60; - qualificationcheck * &#x60;righttoworkcheck&#x60; - righttoworkcheck * &#x60;vogcheck&#x60; - vogcheck * &#x60;watchlist2check&#x60; - watchlist2check * &#x60;watchlistcheck&#x60; - watchlistcheck * &#x60;workreferencecheck&#x60; - workreferencecheck * &#x60;worldwidecreditcheck&#x60; - worldwidecreditcheck
    /// </summary>

    Check_typeEnum toCheck_typeEnum(const utility::string_t& value) const;
    const utility::string_t fromCheck_typeEnum(const Check_typeEnum value) const;


    utility::string_t getNote() const;
    bool noteIsSet() const;
    void unsetNote();
    void setNote(const utility::string_t& value);

    /// <summary>
    /// Links the note to the Check spawned from this ProfileCheck. Wins over check_type.
    /// </summary>
    utility::string_t getProfileCheckId() const;
    bool profileCheckIdIsSet() const;
    void unsetProfile_check_id();
    void setProfileCheckId(const utility::string_t& value);

    /// <summary>
    /// Scope the note to a check type. Ignored when profile_check_id is given.  * &#x60;addresscheck&#x60; - addresscheck * &#x60;adversemedia2check&#x60; - adversemedia2check * &#x60;adversemediacheck&#x60; - adversemediacheck * &#x60;bigcheck&#x60; - bigcheck * &#x60;criminalrecordscheck&#x60; - criminalrecordscheck * &#x60;criminalrecordsuploadcheck&#x60; - criminalrecordsuploadcheck * &#x60;customintegritycheck&#x60; - customintegritycheck * &#x60;cvcheck&#x60; - cvcheck * &#x60;edrcheck&#x60; - edrcheck * &#x60;focumcheck&#x60; - focumcheck * &#x60;id2check&#x60; - id2check * &#x60;idcheck&#x60; - idcheck * &#x60;integritycheck&#x60; - integritycheck * &#x60;openhealthcarecheck&#x60; - openhealthcarecheck * &#x60;permissioncheck&#x60; - permissioncheck * &#x60;pescheckadversemediacheck&#x60; - pescheckadversemediacheck * &#x60;qualificationcheck&#x60; - qualificationcheck * &#x60;righttoworkcheck&#x60; - righttoworkcheck * &#x60;vogcheck&#x60; - vogcheck * &#x60;watchlist2check&#x60; - watchlist2check * &#x60;watchlistcheck&#x60; - watchlistcheck * &#x60;workreferencecheck&#x60; - workreferencecheck * &#x60;worldwidecreditcheck&#x60; - worldwidecreditcheck
    /// </summary>
    Check_typeEnum getCheckType() const;
    bool checkTypeIsSet() const;
    void unsetCheck_type();
    void setCheckType(const Check_typeEnum value);


protected:
    utility::string_t m_Note;
    bool m_NoteIsSet;

    boost::optional<utility::string_t> m_Profile_check_id;

    Check_typeEnum m_Check_type;
    bool m_Check_typeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_V2ScreeningNoteInput_H_ */
