# coding: utf-8

"""
    Pescheck API

    Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DivisionWrite(BaseModel):
    """
    DivisionWrite
    """ # noqa: E501
    id: Optional[UUID] = None
    name: Annotated[str, Field(strict=True, max_length=255)]
    city: Annotated[str, Field(strict=True, max_length=255)]
    address: Annotated[str, Field(strict=True, max_length=255)]
    postal: Annotated[str, Field(strict=True, max_length=20)]
    phone: Annotated[str, Field(strict=True, max_length=20)]
    contact_name: Annotated[str, Field(strict=True, max_length=255)]
    contact_email: StrictStr
    invoice_email: StrictStr
    use_parent_on_email: Optional[StrictBool] = None
    use_parent_on_billing: Optional[StrictBool] = None
    use_parent_on_report: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "name", "city", "address", "postal", "phone", "contact_name", "contact_email", "invoice_email", "use_parent_on_email", "use_parent_on_billing", "use_parent_on_report"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DivisionWrite from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DivisionWrite from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "city": obj.get("city"),
            "address": obj.get("address"),
            "postal": obj.get("postal"),
            "phone": obj.get("phone"),
            "contact_name": obj.get("contact_name"),
            "contact_email": obj.get("contact_email"),
            "invoice_email": obj.get("invoice_email"),
            "use_parent_on_email": obj.get("use_parent_on_email"),
            "use_parent_on_billing": obj.get("use_parent_on_billing"),
            "use_parent_on_report": obj.get("use_parent_on_report")
        })
        return _obj


