/*
 * Pescheck API
 *
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Pescheck.Client.Client;
using Pescheck.Client.Model;

namespace Pescheck.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOAuthApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create OAuth application for API access
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <returns>OAuthApplicationResponse</returns>
        OAuthApplicationResponse CreateOAuthApplication2(OAuthApplication oAuthApplication);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create OAuth application for API access
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <returns>ApiResponse of OAuthApplicationResponse</returns>
        ApiResponse<OAuthApplicationResponse> CreateOAuthApplication2WithHttpInfo(OAuthApplication oAuthApplication);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete an OAuth application
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <returns></returns>
        void DeleteOAuthApplication2(string applicationId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete an OAuth application
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteOAuthApplication2WithHttpInfo(string applicationId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List OAuth applications for the organization
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;OAuthApplicationResponse&gt;</returns>
        List<OAuthApplicationResponse> ListOAuthApplications2();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List OAuth applications for the organization
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;OAuthApplicationResponse&gt;</returns>
        ApiResponse<List<OAuthApplicationResponse>> ListOAuthApplications2WithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOAuthApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create OAuth application for API access
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OAuthApplicationResponse</returns>
        System.Threading.Tasks.Task<OAuthApplicationResponse> CreateOAuthApplication2Async(OAuthApplication oAuthApplication, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create OAuth application for API access
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OAuthApplicationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OAuthApplicationResponse>> CreateOAuthApplication2WithHttpInfoAsync(OAuthApplication oAuthApplication, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete an OAuth application
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteOAuthApplication2Async(string applicationId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete an OAuth application
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteOAuthApplication2WithHttpInfoAsync(string applicationId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List OAuth applications for the organization
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OAuthApplicationResponse&gt;</returns>
        System.Threading.Tasks.Task<List<OAuthApplicationResponse>> ListOAuthApplications2Async(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List OAuth applications for the organization
        /// </remarks>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OAuthApplicationResponse&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<OAuthApplicationResponse>>> ListOAuthApplications2WithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOAuthApi : IOAuthApiSync, IOAuthApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OAuthApi : IDisposable, IOAuthApi
    {
        private Pescheck.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public OAuthApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public OAuthApi(string basePath)
        {
            this.Configuration = Pescheck.Client.Client.Configuration.MergeConfigurations(
                Pescheck.Client.Client.GlobalConfiguration.Instance,
                new Pescheck.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Pescheck.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Pescheck.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public OAuthApi(Pescheck.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Pescheck.Client.Client.Configuration.MergeConfigurations(
                Pescheck.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Pescheck.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Pescheck.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public OAuthApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public OAuthApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Pescheck.Client.Client.Configuration.MergeConfigurations(
                Pescheck.Client.Client.GlobalConfiguration.Instance,
                new Pescheck.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Pescheck.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Pescheck.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public OAuthApi(HttpClient client, Pescheck.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Pescheck.Client.Client.Configuration.MergeConfigurations(
                Pescheck.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Pescheck.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Pescheck.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public OAuthApi(Pescheck.Client.Client.ISynchronousClient client, Pescheck.Client.Client.IAsynchronousClient asyncClient, Pescheck.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Pescheck.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Pescheck.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Pescheck.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Pescheck.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Pescheck.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Pescheck.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Create OAuth application for API access
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <returns>OAuthApplicationResponse</returns>
        public OAuthApplicationResponse CreateOAuthApplication2(OAuthApplication oAuthApplication)
        {
            Pescheck.Client.Client.ApiResponse<OAuthApplicationResponse> localVarResponse = CreateOAuthApplication2WithHttpInfo(oAuthApplication);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create OAuth application for API access
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <returns>ApiResponse of OAuthApplicationResponse</returns>
        public Pescheck.Client.Client.ApiResponse<OAuthApplicationResponse> CreateOAuthApplication2WithHttpInfo(OAuthApplication oAuthApplication)
        {
            // verify the required parameter 'oAuthApplication' is set
            if (oAuthApplication == null)
                throw new Pescheck.Client.Client.ApiException(400, "Missing required parameter 'oAuthApplication' when calling OAuthApi->CreateOAuthApplication2");

            Pescheck.Client.Client.RequestOptions localVarRequestOptions = new Pescheck.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Pescheck.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pescheck.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = oAuthApplication;

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OAuthApplicationResponse>("/api/v2/oauth/applications/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateOAuthApplication2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Create OAuth application for API access
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OAuthApplicationResponse</returns>
        public async System.Threading.Tasks.Task<OAuthApplicationResponse> CreateOAuthApplication2Async(OAuthApplication oAuthApplication, System.Threading.CancellationToken cancellationToken = default)
        {
            Pescheck.Client.Client.ApiResponse<OAuthApplicationResponse> localVarResponse = await CreateOAuthApplication2WithHttpInfoAsync(oAuthApplication, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create OAuth application for API access
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oAuthApplication"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OAuthApplicationResponse)</returns>
        public async System.Threading.Tasks.Task<Pescheck.Client.Client.ApiResponse<OAuthApplicationResponse>> CreateOAuthApplication2WithHttpInfoAsync(OAuthApplication oAuthApplication, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'oAuthApplication' is set
            if (oAuthApplication == null)
                throw new Pescheck.Client.Client.ApiException(400, "Missing required parameter 'oAuthApplication' when calling OAuthApi->CreateOAuthApplication2");


            Pescheck.Client.Client.RequestOptions localVarRequestOptions = new Pescheck.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Pescheck.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pescheck.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = oAuthApplication;

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<OAuthApplicationResponse>("/api/v2/oauth/applications/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateOAuthApplication2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Delete an OAuth application
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <returns></returns>
        public void DeleteOAuthApplication2(string applicationId)
        {
            DeleteOAuthApplication2WithHttpInfo(applicationId);
        }

        /// <summary>
        ///  Delete an OAuth application
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Pescheck.Client.Client.ApiResponse<Object> DeleteOAuthApplication2WithHttpInfo(string applicationId)
        {
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new Pescheck.Client.Client.ApiException(400, "Missing required parameter 'applicationId' when calling OAuthApi->DeleteOAuthApplication2");

            Pescheck.Client.Client.RequestOptions localVarRequestOptions = new Pescheck.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Pescheck.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pescheck.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("application_id", Pescheck.Client.Client.ClientUtils.ParameterToString(applicationId)); // path parameter

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/v2/oauth/applications/{application_id}/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteOAuthApplication2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Delete an OAuth application
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteOAuthApplication2Async(string applicationId, System.Threading.CancellationToken cancellationToken = default)
        {
            await DeleteOAuthApplication2WithHttpInfoAsync(applicationId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Delete an OAuth application
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="applicationId">Application ID to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Pescheck.Client.Client.ApiResponse<Object>> DeleteOAuthApplication2WithHttpInfoAsync(string applicationId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new Pescheck.Client.Client.ApiException(400, "Missing required parameter 'applicationId' when calling OAuthApi->DeleteOAuthApplication2");


            Pescheck.Client.Client.RequestOptions localVarRequestOptions = new Pescheck.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = Pescheck.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pescheck.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("application_id", Pescheck.Client.Client.ClientUtils.ParameterToString(applicationId)); // path parameter

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/v2/oauth/applications/{application_id}/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteOAuthApplication2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  List OAuth applications for the organization
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;OAuthApplicationResponse&gt;</returns>
        public List<OAuthApplicationResponse> ListOAuthApplications2()
        {
            Pescheck.Client.Client.ApiResponse<List<OAuthApplicationResponse>> localVarResponse = ListOAuthApplications2WithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  List OAuth applications for the organization
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;OAuthApplicationResponse&gt;</returns>
        public Pescheck.Client.Client.ApiResponse<List<OAuthApplicationResponse>> ListOAuthApplications2WithHttpInfo()
        {
            Pescheck.Client.Client.RequestOptions localVarRequestOptions = new Pescheck.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Pescheck.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pescheck.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<OAuthApplicationResponse>>("/api/v2/oauth/applications/list/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListOAuthApplications2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  List OAuth applications for the organization
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OAuthApplicationResponse&gt;</returns>
        public async System.Threading.Tasks.Task<List<OAuthApplicationResponse>> ListOAuthApplications2Async(System.Threading.CancellationToken cancellationToken = default)
        {
            Pescheck.Client.Client.ApiResponse<List<OAuthApplicationResponse>> localVarResponse = await ListOAuthApplications2WithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  List OAuth applications for the organization
        /// </summary>
        /// <exception cref="Pescheck.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OAuthApplicationResponse&gt;)</returns>
        public async System.Threading.Tasks.Task<Pescheck.Client.Client.ApiResponse<List<OAuthApplicationResponse>>> ListOAuthApplications2WithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Pescheck.Client.Client.RequestOptions localVarRequestOptions = new Pescheck.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Pescheck.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Pescheck.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<OAuthApplicationResponse>>("/api/v2/oauth/applications/list/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListOAuthApplications2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
