/* tslint:disable */
/* eslint-disable */
/**
 * Pescheck API
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type OrganisationAddon,
    OrganisationAddonFromJSON,
    OrganisationAddonToJSON,
} from '../models/OrganisationAddon';
import {
    type OrganisationAddonUpdate,
    OrganisationAddonUpdateFromJSON,
    OrganisationAddonUpdateToJSON,
} from '../models/OrganisationAddonUpdate';
import {
    type OrganisationAddonUpdateResult,
    OrganisationAddonUpdateResultFromJSON,
    OrganisationAddonUpdateResultToJSON,
} from '../models/OrganisationAddonUpdateResult';
import {
    type PatchedOrganisationAddonUpdate,
    PatchedOrganisationAddonUpdateFromJSON,
    PatchedOrganisationAddonUpdateToJSON,
} from '../models/PatchedOrganisationAddonUpdate';

export interface V2OrganisationsAddonsListRequest {
    divisionId?: string;
}

export interface V2OrganisationsAddonsPartialUpdateRequest {
    addon: V2OrganisationsAddonsPartialUpdateAddonEnum;
    divisionId?: string;
    patchedOrganisationAddonUpdate?: PatchedOrganisationAddonUpdate;
}

export interface V2OrganisationsAddonsRetrieveRequest {
    addon: V2OrganisationsAddonsRetrieveAddonEnum;
    divisionId?: string;
}

export interface V2OrganisationsAddonsUpdateRequest {
    addon: V2OrganisationsAddonsUpdateAddonEnum;
    organisationAddonUpdate: OrganisationAddonUpdate;
    divisionId?: string;
}

/**
 * AddOnsApi - interface
 * 
 * @export
 * @interface AddOnsApiInterface
 */
export interface AddOnsApiInterface {
    /**
     * Creates request options for v2OrganisationsAddonsList without sending the request
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsListRequestOpts(requestParameters: V2OrganisationsAddonsListRequest): Promise<runtime.RequestOpts>;

    /**
     * List every add-on with whether it is enabled for the organisation.
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsListRaw(requestParameters: V2OrganisationsAddonsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganisationAddon>>>;

    /**
     * List every add-on with whether it is enabled for the organisation.
     */
    v2OrganisationsAddonsList(requestParameters: V2OrganisationsAddonsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganisationAddon>>;

    /**
     * Creates request options for v2OrganisationsAddonsPartialUpdate without sending the request
     * @param {'api_access' | 'branded_journey' | 'connected_ats' | 'sso'} addon The add-on to act on.
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @param {PatchedOrganisationAddonUpdate} [patchedOrganisationAddonUpdate] 
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsPartialUpdateRequestOpts(requestParameters: V2OrganisationsAddonsPartialUpdateRequest): Promise<runtime.RequestOpts>;

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     * @param {'api_access' | 'branded_journey' | 'connected_ats' | 'sso'} addon The add-on to act on.
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @param {PatchedOrganisationAddonUpdate} [patchedOrganisationAddonUpdate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsPartialUpdateRaw(requestParameters: V2OrganisationsAddonsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationAddonUpdateResult>>;

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     */
    v2OrganisationsAddonsPartialUpdate(requestParameters: V2OrganisationsAddonsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationAddonUpdateResult>;

    /**
     * Creates request options for v2OrganisationsAddonsRetrieve without sending the request
     * @param {'api_access' | 'branded_journey' | 'connected_ats' | 'sso'} addon The add-on to act on.
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsRetrieveRequestOpts(requestParameters: V2OrganisationsAddonsRetrieveRequest): Promise<runtime.RequestOpts>;

    /**
     * Get one add-on\'s state for the organisation.
     * @param {'api_access' | 'branded_journey' | 'connected_ats' | 'sso'} addon The add-on to act on.
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsRetrieveRaw(requestParameters: V2OrganisationsAddonsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationAddon>>;

    /**
     * Get one add-on\'s state for the organisation.
     */
    v2OrganisationsAddonsRetrieve(requestParameters: V2OrganisationsAddonsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationAddon>;

    /**
     * Creates request options for v2OrganisationsAddonsUpdate without sending the request
     * @param {'api_access' | 'branded_journey' | 'connected_ats' | 'sso'} addon The add-on to act on.
     * @param {OrganisationAddonUpdate} organisationAddonUpdate 
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsUpdateRequestOpts(requestParameters: V2OrganisationsAddonsUpdateRequest): Promise<runtime.RequestOpts>;

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     * @param {'api_access' | 'branded_journey' | 'connected_ats' | 'sso'} addon The add-on to act on.
     * @param {OrganisationAddonUpdate} organisationAddonUpdate 
     * @param {string} [divisionId] Act on this division instead of the organisation the token belongs to.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddOnsApiInterface
     */
    v2OrganisationsAddonsUpdateRaw(requestParameters: V2OrganisationsAddonsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationAddonUpdateResult>>;

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     */
    v2OrganisationsAddonsUpdate(requestParameters: V2OrganisationsAddonsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationAddonUpdateResult>;

}

/**
 * 
 */
export class AddOnsApi extends runtime.BaseAPI implements AddOnsApiInterface {

    /**
     * Creates request options for v2OrganisationsAddonsList without sending the request
     */
    async v2OrganisationsAddonsListRequestOpts(requestParameters: V2OrganisationsAddonsListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['divisionId'] != null) {
            queryParameters['division_id'] = requestParameters['divisionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = `Bearer ${await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"])}`;
        }


        let urlPath = `/api/v2/organisations/addons/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List every add-on with whether it is enabled for the organisation.
     */
    async v2OrganisationsAddonsListRaw(requestParameters: V2OrganisationsAddonsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganisationAddon>>> {
        const requestOptions = await this.v2OrganisationsAddonsListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganisationAddonFromJSON));
    }

    /**
     * List every add-on with whether it is enabled for the organisation.
     */
    async v2OrganisationsAddonsList(requestParameters: V2OrganisationsAddonsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganisationAddon>> {
        const response = await this.v2OrganisationsAddonsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v2OrganisationsAddonsPartialUpdate without sending the request
     */
    async v2OrganisationsAddonsPartialUpdateRequestOpts(requestParameters: V2OrganisationsAddonsPartialUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['addon'] == null) {
            throw new runtime.RequiredError(
                'addon',
                'Required parameter "addon" was null or undefined when calling v2OrganisationsAddonsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['divisionId'] != null) {
            queryParameters['division_id'] = requestParameters['divisionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = `Bearer ${await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"])}`;
        }


        let urlPath = `/api/v2/organisations/addons/{addon}/`;
        urlPath = urlPath.replace('{addon}', encodeURIComponent(String(requestParameters['addon'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedOrganisationAddonUpdateToJSON(requestParameters['patchedOrganisationAddonUpdate']),
        };
    }

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     */
    async v2OrganisationsAddonsPartialUpdateRaw(requestParameters: V2OrganisationsAddonsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationAddonUpdateResult>> {
        const requestOptions = await this.v2OrganisationsAddonsPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationAddonUpdateResultFromJSON(jsonValue));
    }

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     */
    async v2OrganisationsAddonsPartialUpdate(requestParameters: V2OrganisationsAddonsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationAddonUpdateResult> {
        const response = await this.v2OrganisationsAddonsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v2OrganisationsAddonsRetrieve without sending the request
     */
    async v2OrganisationsAddonsRetrieveRequestOpts(requestParameters: V2OrganisationsAddonsRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['addon'] == null) {
            throw new runtime.RequiredError(
                'addon',
                'Required parameter "addon" was null or undefined when calling v2OrganisationsAddonsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['divisionId'] != null) {
            queryParameters['division_id'] = requestParameters['divisionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = `Bearer ${await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"])}`;
        }


        let urlPath = `/api/v2/organisations/addons/{addon}/`;
        urlPath = urlPath.replace('{addon}', encodeURIComponent(String(requestParameters['addon'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one add-on\'s state for the organisation.
     */
    async v2OrganisationsAddonsRetrieveRaw(requestParameters: V2OrganisationsAddonsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationAddon>> {
        const requestOptions = await this.v2OrganisationsAddonsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationAddonFromJSON(jsonValue));
    }

    /**
     * Get one add-on\'s state for the organisation.
     */
    async v2OrganisationsAddonsRetrieve(requestParameters: V2OrganisationsAddonsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationAddon> {
        const response = await this.v2OrganisationsAddonsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v2OrganisationsAddonsUpdate without sending the request
     */
    async v2OrganisationsAddonsUpdateRequestOpts(requestParameters: V2OrganisationsAddonsUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['addon'] == null) {
            throw new runtime.RequiredError(
                'addon',
                'Required parameter "addon" was null or undefined when calling v2OrganisationsAddonsUpdate().'
            );
        }

        if (requestParameters['organisationAddonUpdate'] == null) {
            throw new runtime.RequiredError(
                'organisationAddonUpdate',
                'Required parameter "organisationAddonUpdate" was null or undefined when calling v2OrganisationsAddonsUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['divisionId'] != null) {
            queryParameters['division_id'] = requestParameters['divisionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = `Bearer ${await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"])}`;
        }


        let urlPath = `/api/v2/organisations/addons/{addon}/`;
        urlPath = urlPath.replace('{addon}', encodeURIComponent(String(requestParameters['addon'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrganisationAddonUpdateToJSON(requestParameters['organisationAddonUpdate']),
        };
    }

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     */
    async v2OrganisationsAddonsUpdateRaw(requestParameters: V2OrganisationsAddonsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganisationAddonUpdateResult>> {
        const requestOptions = await this.v2OrganisationsAddonsUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationAddonUpdateResultFromJSON(jsonValue));
    }

    /**
     * Switch an add-on on or off. Enabling is billed monthly from today.
     */
    async v2OrganisationsAddonsUpdate(requestParameters: V2OrganisationsAddonsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganisationAddonUpdateResult> {
        const response = await this.v2OrganisationsAddonsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const V2OrganisationsAddonsPartialUpdateAddonEnum = {
    ApiAccess: 'api_access',
    BrandedJourney: 'branded_journey',
    ConnectedAts: 'connected_ats',
    Sso: 'sso'
} as const;
export type V2OrganisationsAddonsPartialUpdateAddonEnum = typeof V2OrganisationsAddonsPartialUpdateAddonEnum[keyof typeof V2OrganisationsAddonsPartialUpdateAddonEnum];
/**
 * @export
 */
export const V2OrganisationsAddonsRetrieveAddonEnum = {
    ApiAccess: 'api_access',
    BrandedJourney: 'branded_journey',
    ConnectedAts: 'connected_ats',
    Sso: 'sso'
} as const;
export type V2OrganisationsAddonsRetrieveAddonEnum = typeof V2OrganisationsAddonsRetrieveAddonEnum[keyof typeof V2OrganisationsAddonsRetrieveAddonEnum];
/**
 * @export
 */
export const V2OrganisationsAddonsUpdateAddonEnum = {
    ApiAccess: 'api_access',
    BrandedJourney: 'branded_journey',
    ConnectedAts: 'connected_ats',
    Sso: 'sso'
} as const;
export type V2OrganisationsAddonsUpdateAddonEnum = typeof V2OrganisationsAddonsUpdateAddonEnum[keyof typeof V2OrganisationsAddonsUpdateAddonEnum];
