/* tslint:disable */
/* eslint-disable */
/**
 * Pescheck API
 * API for Pescheck  ## Authentication This API supports three authentication methods: 1. **OAuth2** (recommended for API clients) - Use client credentials flow 2. **JWT Bearer** (for user-based access) - Obtain tokens via /api/jwt/ endpoint 3. **Cookie** (for browser-based access) - Session authentication via web login  ## Quick Start for API Clients 1. Select your environment from the servers dropdown 2. Use OAuth2 with client credentials flow 3. Scopes are automatically included: read:api, create:api, update:api
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PaginatedV2ScreeningListItemList,
    PaginatedV2ScreeningListItemListFromJSON,
    PaginatedV2ScreeningListItemListToJSON,
} from '../models/PaginatedV2ScreeningListItemList';
import {
    type V2Document,
    V2DocumentFromJSON,
    V2DocumentToJSON,
} from '../models/V2Document';
import {
    type V2ScreeningCreate,
    V2ScreeningCreateFromJSON,
    V2ScreeningCreateToJSON,
} from '../models/V2ScreeningCreate';
import {
    type V2ScreeningDetail,
    V2ScreeningDetailFromJSON,
    V2ScreeningDetailToJSON,
} from '../models/V2ScreeningDetail';

export interface V2ScreeningsCreateRequest {
    v2ScreeningCreate: V2ScreeningCreate;
}

export interface V2ScreeningsDocumentsListRequest {
    id: string;
    checkId?: string;
    checkType?: string;
}

export interface V2ScreeningsListRequest {
    page?: number;
    pageSize?: number;
    paginate?: boolean;
}

export interface V2ScreeningsRetrieveRequest {
    id: string;
}

/**
 * ScreeningsApi - interface
 * 
 * @export
 * @interface ScreeningsApiInterface
 */
export interface ScreeningsApiInterface {
    /**
     * Creates request options for v2ScreeningsCreate without sending the request
     * @param {V2ScreeningCreate} v2ScreeningCreate 
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsCreateRequestOpts(requestParameters: V2ScreeningsCreateRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {V2ScreeningCreate} v2ScreeningCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsCreateRaw(requestParameters: V2ScreeningsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V2ScreeningDetail>>;

    /**
     */
    v2ScreeningsCreate(requestParameters: V2ScreeningsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V2ScreeningDetail>;

    /**
     * Creates request options for v2ScreeningsDocumentsList without sending the request
     * @param {string} id 
     * @param {string} [checkId] Only documents from the check with this id.
     * @param {string} [checkType] Only documents from checks of this type.
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsDocumentsListRequestOpts(requestParameters: V2ScreeningsDocumentsListRequest): Promise<runtime.RequestOpts>;

    /**
     * Documents attached to the screening\'s checks. Files are delivered inline as Base64 in `content`. Narrow the result with `check_id` or `check_type`.
     * @summary Retrieve screening documents
     * @param {string} id 
     * @param {string} [checkId] Only documents from the check with this id.
     * @param {string} [checkType] Only documents from checks of this type.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsDocumentsListRaw(requestParameters: V2ScreeningsDocumentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<V2Document>>>;

    /**
     * Documents attached to the screening\'s checks. Files are delivered inline as Base64 in `content`. Narrow the result with `check_id` or `check_type`.
     * Retrieve screening documents
     */
    v2ScreeningsDocumentsList(requestParameters: V2ScreeningsDocumentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<V2Document>>;

    /**
     * Creates request options for v2ScreeningsList without sending the request
     * @param {number} [page] A page number within the paginated result set.
     * @param {number} [pageSize] Number of results to return per page.
     * @param {boolean} [paginate] Enable/disable pagination. When false, max 500 records returned.
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsListRequestOpts(requestParameters: V2ScreeningsListRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} [page] A page number within the paginated result set.
     * @param {number} [pageSize] Number of results to return per page.
     * @param {boolean} [paginate] Enable/disable pagination. When false, max 500 records returned.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsListRaw(requestParameters: V2ScreeningsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedV2ScreeningListItemList>>;

    /**
     */
    v2ScreeningsList(requestParameters: V2ScreeningsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedV2ScreeningListItemList>;

    /**
     * Creates request options for v2ScreeningsRetrieve without sending the request
     * @param {string} id A UUID string identifying this screening.
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsRetrieveRequestOpts(requestParameters: V2ScreeningsRetrieveRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id A UUID string identifying this screening.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScreeningsApiInterface
     */
    v2ScreeningsRetrieveRaw(requestParameters: V2ScreeningsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V2ScreeningDetail>>;

    /**
     */
    v2ScreeningsRetrieve(requestParameters: V2ScreeningsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V2ScreeningDetail>;

}

/**
 * 
 */
export class ScreeningsApi extends runtime.BaseAPI implements ScreeningsApiInterface {

    /**
     * Creates request options for v2ScreeningsCreate without sending the request
     */
    async v2ScreeningsCreateRequestOpts(requestParameters: V2ScreeningsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['v2ScreeningCreate'] == null) {
            throw new runtime.RequiredError(
                'v2ScreeningCreate',
                'Required parameter "v2ScreeningCreate" was null or undefined when calling v2ScreeningsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }


        let urlPath = `/api/v2/screenings/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V2ScreeningCreateToJSON(requestParameters['v2ScreeningCreate']),
        };
    }

    /**
     */
    async v2ScreeningsCreateRaw(requestParameters: V2ScreeningsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V2ScreeningDetail>> {
        const requestOptions = await this.v2ScreeningsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V2ScreeningDetailFromJSON(jsonValue));
    }

    /**
     */
    async v2ScreeningsCreate(requestParameters: V2ScreeningsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V2ScreeningDetail> {
        const response = await this.v2ScreeningsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v2ScreeningsDocumentsList without sending the request
     */
    async v2ScreeningsDocumentsListRequestOpts(requestParameters: V2ScreeningsDocumentsListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v2ScreeningsDocumentsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['checkId'] != null) {
            queryParameters['check_id'] = requestParameters['checkId'];
        }

        if (requestParameters['checkType'] != null) {
            queryParameters['check_type'] = requestParameters['checkType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }


        let urlPath = `/api/v2/screenings/{id}/documents/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Documents attached to the screening\'s checks. Files are delivered inline as Base64 in `content`. Narrow the result with `check_id` or `check_type`.
     * Retrieve screening documents
     */
    async v2ScreeningsDocumentsListRaw(requestParameters: V2ScreeningsDocumentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<V2Document>>> {
        const requestOptions = await this.v2ScreeningsDocumentsListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(V2DocumentFromJSON));
    }

    /**
     * Documents attached to the screening\'s checks. Files are delivered inline as Base64 in `content`. Narrow the result with `check_id` or `check_type`.
     * Retrieve screening documents
     */
    async v2ScreeningsDocumentsList(requestParameters: V2ScreeningsDocumentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<V2Document>> {
        const response = await this.v2ScreeningsDocumentsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v2ScreeningsList without sending the request
     */
    async v2ScreeningsListRequestOpts(requestParameters: V2ScreeningsListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['paginate'] != null) {
            queryParameters['paginate'] = requestParameters['paginate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }


        let urlPath = `/api/v2/screenings/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async v2ScreeningsListRaw(requestParameters: V2ScreeningsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedV2ScreeningListItemList>> {
        const requestOptions = await this.v2ScreeningsListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedV2ScreeningListItemListFromJSON(jsonValue));
    }

    /**
     */
    async v2ScreeningsList(requestParameters: V2ScreeningsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedV2ScreeningListItemList> {
        const response = await this.v2ScreeningsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v2ScreeningsRetrieve without sending the request
     */
    async v2ScreeningsRetrieveRequestOpts(requestParameters: V2ScreeningsRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v2ScreeningsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["read:api", "create:api", "update:api"]);
        }


        let urlPath = `/api/v2/screenings/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async v2ScreeningsRetrieveRaw(requestParameters: V2ScreeningsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V2ScreeningDetail>> {
        const requestOptions = await this.v2ScreeningsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V2ScreeningDetailFromJSON(jsonValue));
    }

    /**
     */
    async v2ScreeningsRetrieve(requestParameters: V2ScreeningsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V2ScreeningDetail> {
        const response = await this.v2ScreeningsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
