<?php
/**
 * ProfilesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Pescheck\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pescheck API
 *
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Pescheck\Client\Test\Api;

use \Pescheck\Client\Configuration;
use \Pescheck\Client\ApiException;
use \Pescheck\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pescheck\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProfilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v2ProfilesCreate
     *
     * .
     *
     */
    public function testV2ProfilesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2ProfilesDestroy
     *
     * .
     *
     */
    public function testV2ProfilesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2ProfilesList
     *
     * .
     *
     */
    public function testV2ProfilesList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2ProfilesPartialUpdate
     *
     * .
     *
     */
    public function testV2ProfilesPartialUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2ProfilesRetrieve
     *
     * .
     *
     */
    public function testV2ProfilesRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2ProfilesUpdate
     *
     * .
     *
     */
    public function testV2ProfilesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
