<?php
/**
 * OrganisationAddonUpdateResult
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pescheck\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pescheck API
 *
 * Official client library for the Pescheck API (v2), generated from the OpenAPI specification. Authenticate with OAuth2 client credentials and use the checks, profiles, screenings, webhooks and divisions endpoints. See https://github.com/pescheckit/pescheck-clients for installation and usage.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pescheck\Client\Model;

use \ArrayAccess;
use \Pescheck\Client\ObjectSerializer;

/**
 * OrganisationAddonUpdateResult Class Doc Comment
 *
 * @category Class
 * @description One add-on for one organisation, built from &#x60;&#x60;addon_service.addon_cards&#x60;&#x60;.
 * @package  Pescheck\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrganisationAddonUpdateResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'OrganisationAddonUpdateResult';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'addon' => 'string',
        'name' => 'string',
        'description' => 'string',
        'enabled' => 'bool',
        'active' => 'bool',
        'blocked_by_parent' => 'bool',
        'monthly_price' => '\Pescheck\Client\Model\AddonPrice',
        'price_is_indicative' => 'bool',
        'disabled_divisions' => '\Pescheck\Client\Model\DisabledDivision[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'addon' => null,
        'name' => null,
        'description' => null,
        'enabled' => null,
        'active' => null,
        'blocked_by_parent' => null,
        'monthly_price' => null,
        'price_is_indicative' => null,
        'disabled_divisions' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'addon' => false,
        'name' => false,
        'description' => false,
        'enabled' => false,
        'active' => false,
        'blocked_by_parent' => false,
        'monthly_price' => true,
        'price_is_indicative' => false,
        'disabled_divisions' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'addon' => 'addon',
        'name' => 'name',
        'description' => 'description',
        'enabled' => 'enabled',
        'active' => 'active',
        'blocked_by_parent' => 'blocked_by_parent',
        'monthly_price' => 'monthly_price',
        'price_is_indicative' => 'price_is_indicative',
        'disabled_divisions' => 'disabled_divisions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'addon' => 'setAddon',
        'name' => 'setName',
        'description' => 'setDescription',
        'enabled' => 'setEnabled',
        'active' => 'setActive',
        'blocked_by_parent' => 'setBlockedByParent',
        'monthly_price' => 'setMonthlyPrice',
        'price_is_indicative' => 'setPriceIsIndicative',
        'disabled_divisions' => 'setDisabledDivisions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'addon' => 'getAddon',
        'name' => 'getName',
        'description' => 'getDescription',
        'enabled' => 'getEnabled',
        'active' => 'getActive',
        'blocked_by_parent' => 'getBlockedByParent',
        'monthly_price' => 'getMonthlyPrice',
        'price_is_indicative' => 'getPriceIsIndicative',
        'disabled_divisions' => 'getDisabledDivisions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ADDON_BRANDED_JOURNEY = 'branded_journey';
    public const ADDON_SSO = 'sso';
    public const ADDON_API_ACCESS = 'api_access';
    public const ADDON_CONNECTED_ATS = 'connected_ats';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAddonAllowableValues()
    {
        return [
            self::ADDON_BRANDED_JOURNEY,
            self::ADDON_SSO,
            self::ADDON_API_ACCESS,
            self::ADDON_CONNECTED_ATS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('addon', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('blocked_by_parent', $data ?? [], null);
        $this->setIfExists('monthly_price', $data ?? [], null);
        $this->setIfExists('price_is_indicative', $data ?? [], null);
        $this->setIfExists('disabled_divisions', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['addon'] === null) {
            $invalidProperties[] = "'addon' can't be null";
        }
        $allowedValues = $this->getAddonAllowableValues();
        if (!is_null($this->container['addon']) && !in_array($this->container['addon'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'addon', must be one of '%s'",
                $this->container['addon'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['enabled'] === null) {
            $invalidProperties[] = "'enabled' can't be null";
        }
        if ($this->container['active'] === null) {
            $invalidProperties[] = "'active' can't be null";
        }
        if ($this->container['blocked_by_parent'] === null) {
            $invalidProperties[] = "'blocked_by_parent' can't be null";
        }
        if ($this->container['monthly_price'] === null && !$this->isNullableSetToNull('monthly_price')) {
            $invalidProperties[] = "'monthly_price' is required";
        }
        if ($this->container['price_is_indicative'] === null) {
            $invalidProperties[] = "'price_is_indicative' can't be null";
        }
        if ($this->container['disabled_divisions'] === null) {
            $invalidProperties[] = "'disabled_divisions' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets addon
     *
     * @return string
     */
    public function getAddon()
    {
        return $this->container['addon'];
    }

    /**
     * Sets addon
     *
     * @param string $addon Add-on identifier, used in the URL.  * `branded_journey` - Branded Journey * `sso` - Single Sign-On (SSO) * `api_access` - API Access * `connected_ats` - Connected ATS - Click & Go
     *
     * @return self
     */
    public function setAddon($addon)
    {
        if (is_null($addon)) {
            throw new \InvalidArgumentException('non-nullable addon cannot be null');
        }
        $allowedValues = $this->getAddonAllowableValues();
        if (!in_array($addon, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'addon', must be one of '%s'",
                    $addon,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['addon'] = $addon;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool $enabled Switched on (and billed) for this organisation.
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool $active Usable right now. A division also needs the add-on on its parent organisation.
     *
     * @return self
     */
    public function setActive($active)
    {
        if (is_null($active)) {
            throw new \InvalidArgumentException('non-nullable active cannot be null');
        }
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets blocked_by_parent
     *
     * @return bool
     */
    public function getBlockedByParent()
    {
        return $this->container['blocked_by_parent'];
    }

    /**
     * Sets blocked_by_parent
     *
     * @param bool $blocked_by_parent Only the missing add-on on the parent organisation stands in the way.
     *
     * @return self
     */
    public function setBlockedByParent($blocked_by_parent)
    {
        if (is_null($blocked_by_parent)) {
            throw new \InvalidArgumentException('non-nullable blocked_by_parent cannot be null');
        }
        $this->container['blocked_by_parent'] = $blocked_by_parent;

        return $this;
    }

    /**
     * Gets monthly_price
     *
     * @return \Pescheck\Client\Model\AddonPrice|null
     */
    public function getMonthlyPrice()
    {
        return $this->container['monthly_price'];
    }

    /**
     * Sets monthly_price
     *
     * @param \Pescheck\Client\Model\AddonPrice|null $monthly_price What this organisation pays per month; the division price for a division. Null when unpriced.
     *
     * @return self
     */
    public function setMonthlyPrice($monthly_price)
    {
        if (is_null($monthly_price)) {
            array_push($this->openAPINullablesSetToNull, 'monthly_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('monthly_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['monthly_price'] = $monthly_price;

        return $this;
    }

    /**
     * Gets price_is_indicative
     *
     * @return bool
     */
    public function getPriceIsIndicative()
    {
        return $this->container['price_is_indicative'];
    }

    /**
     * Sets price_is_indicative
     *
     * @param bool $price_is_indicative The price is a starting price (\"from\").
     *
     * @return self
     */
    public function setPriceIsIndicative($price_is_indicative)
    {
        if (is_null($price_is_indicative)) {
            throw new \InvalidArgumentException('non-nullable price_is_indicative cannot be null');
        }
        $this->container['price_is_indicative'] = $price_is_indicative;

        return $this;
    }

    /**
     * Gets disabled_divisions
     *
     * @return \Pescheck\Client\Model\DisabledDivision[]
     */
    public function getDisabledDivisions()
    {
        return $this->container['disabled_divisions'];
    }

    /**
     * Sets disabled_divisions
     *
     * @param \Pescheck\Client\Model\DisabledDivision[] $disabled_divisions Divisions that were switched off too, because the add-on was switched off on their parent.
     *
     * @return self
     */
    public function setDisabledDivisions($disabled_divisions)
    {
        if (is_null($disabled_divisions)) {
            throw new \InvalidArgumentException('non-nullable disabled_divisions cannot be null');
        }
        $this->container['disabled_divisions'] = $disabled_divisions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


